### ISSUE TITLE
Add DOM functions (API)

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#1]
Model manipulation requires a good knowledge of Archi internal API. This is quite easy when working solely with the model concepts, but can become hard when dealing with views.

Some helper functions could help:
- ListOfElements getElementsInView(v View)
- ListOfRelationships getRelationshipsInView(v View)
- ListOfConcepts getConceptsInView(v View)

Those are only examples, we might try to design a good API that could be completed over time.

**Comment by Phillipus** [comment]
Some more ideas from @jbsarrodie captured here:

'model' would be a binded variable which points to the current model

'selection' would be a binded variable which point to the current selection of concepts or views

'$(model)' would allow basic model level manipulation like:

- $(model) would simply return the model, for convenience, and to mimic "$(document)' JQuery notation
- $(model).load(path_to_the_model) to load a new model
- $(model).save(optional_path_to_the_model) to save the model
- $(model).openInUI to open the model in Archi UI (if this makes sens)
- $(model).addElement(type, name) would add an element of type "type" with name "name" and return a collection
- $(model).addRelationship(type, name, source, target) would add a relationship of type "type" with name "name" having "source" (a collection that must contains only one concept) as source and "target" (a collection that must contains only one concept) as target, given that the relationship is allowed. Return a collection

- '$(selector)' would use selector (string) as a kind of CSS selector on concepts and views:

- $(selection) would simply return the selection (collection) for convenience. In fact $(any_collection) would return the collection.
- $("#uniq_id") would return a collection with only one item: the concepts/view which Id was passed as argument, with '#' added before.
- $(".name") would return a collection with all concepts/views that have the name passed as argument, with '.' added before. Name is equivalent to a CSS class.
- $("type") would return a collection with all concepts/views that match the type passed as argument. Type can be any of the ArchiMate elements and relationship types, or some "pseudo-types" like "business-elements", "strategy-elements", "elements", "concepts", "views"...
- $("type.name") would return a collection with all concepts/views matching the type and name.
- $() would return a collection with all concepts/views

Then we could do the following on a collection:

In general, all methods should be invoked on a collection, but they should work the same if invoked on a single item (thus a wrapper or proxy). Ie on should be able to manipulate collection or individuals the exact same way.

In general, ".add", ".remove", ".set" methods return the updated collection while ".get" methods return an array of (array of) string.

- .getId() would return an array containing ids of objects contained into the collection
- .getName() would return an array containing names of objects contained into the collection
- .setName(new_name) would update all objects of the collection to match the given new_name. Returns the updated collection.
- .getDocumentation() would return an array of documentations
- .setDocumentation() would update the documentation for each objects of the collection and return the updated collection.
- .getSource() would return a collection containing the source of each relationship contained into the input collection
- .getSourceId() would return an array of Id (ie. string)
- .getTarget() same as getSource but for target ;-)
- .getTargetId() ...
- .getEnds() would return a collection containing sources and targets for each relationship contained into the input collection
- .getEndsId() would return an array of array of Ids in the form [ [src1, tgt1], [src2, tgt2], [src3....
- .getPropertyKey() would return an array of string containing the list of properties keys that exist on collection's members. A key appears only once (ie: duplicates are removed)
- .getPropertyValue(key) would return an array of array containing the value of property named "key" for each object of the collection. This has to be an array of array because the propery can appear more than once on a same object
- .addProperty(key, value) would add the property on each object of the collection and return the collection. Objects can end up have multiple property with the same name.
- .addOrUpdateProperty(key, value) would add the property only if it doesn't already exists, or update it if it does. If an object already has multiple properties matching the name, all of them are updated. Returns the updated collection
- .removeProperty(key) would remove (all instances of) property "key" on each object of the collection. Returns the updated collection
- .removeProperty(key, value) would remove (all instances of) property "key" that matches "value" on each object of the collection. Returns the updated collection.

**Comment by Phillipus** [comment]
Many of these ideas are now implemented. We need to:

- review the ones we have
- agree the return types whether a single object is more suitable than a collection
- add new ones as required

**Comment by jbsarrodie** [comment]
Some comments here:
* First, that's a really great job done!
* Credits where credits is due: this API is clearly inspired by [jQuery](https://github.com/jquery/jquery).
* I'm going to check and document this API in our wiki. Documentation (with examples) is key for people to use it.

As you've already used it on Twitter, I think we can agree on a name for this API: jArchi !

**Comment by jbsarrodie** [comment]
*Currently checking jArchi API and listing here remarks or issues. This comment will be updated over time.*

Documentation (work in progress) is available in the [wiki](https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-API-documentation).

I'm copying here current documentation which describes the desired API (ie. the one that best matches jQuery API when possible as this is a key principle). Comments are added below each description.

>#### All Selector ("*")
>````js
>$("*")
>````
Only return concepts and view, but should return also the ArchimateModel itself and Folders.

>#### Object Selector ("type")
>Select all objects with the given type.
>````js
>$("BusinessObject") // => collection containing all Business Objects
>````
It could be good to allow lower case argument ("businessobject" instead of "BusinessObject").

>#### Views Select ("views")
>Select all views (ArchiMate, Sketch, Canvas).
>````js
>$("views") // => collection
>````
It would be good to add selector for ArchiMate, Sketch and Canvas views. Not sure about the best selector name ("archimate-view", "archimateview"....).

>#### .attr()
>Get the value of an attribute for the first object in the set of matched object or set one or more attributes for every matched object.
>````js
>$(element).attr(attrName) // => AttributeValue
>$(element).attr(attrName, attrValue) // => collection
>````
The jQuery way of doing it is to get the attribute value of the **first** object in the collection, not an array of attribute. This seems a better approach. I've a patch that changes this behavior. The same remark is true for all methods that return an attribute (getId, getName...).
In addition, I think that .getSource(), .getSourceId(), .getTarget(), .getTargetId(), getEnds() and getEndsId() are not needed as is but should be addressed through .attr("source") and .attr("target").

>#### .prop()
>If no arguments are provided, return the list of properties' key for the first object in the collection. 
>Return a property value of the first object in the collection when just property is supplied. If multiple properties exist with the same key, then return only the first one (duplicate=false, which is the default) or an array with all values (duplicate=true).
>Sets a property for every objects when property and value are supplied. Property is updated if it already exists (duplicate=false, which is the default) or added anyway (duplicate=true).
>````js
>$(element).prop() //=> properties' key for the first object
>$(element).prop(property) // => property value (first one if multiple entries)
>$(element).prop(property, false) // => property value (first one if multiple entries)
>$(element).prop(property, true) // => property value (array if multiple entries)
>$(element).prop(property, value) // => updated collection with property added (if it did not exist) or updated (if it existed)
>$(element).prop(property, value, false) // => updated collection with property added (if it not existed) or updated (if it existed)
>$(element).prop(property, value, true) // => updated collection with property added (even if it existed)
>````
The described API is more in line with jQuery API. I've just extended it a bit to allow duplicate key handling. This should replace getPropertyValue(propKey), addProperty(propKey, propValue) and addOrUpdateProperty(propKey, propValue).

>#### .removeProp()
>Removes property from collection elements.
>````js
>$(element).removeProp(propName) // => all instances of propName are removed
>$(element).removeProp(propName, propValue) // => properties are removed if value matches propValue
>````
The described API is more in line with jQuery API. This should replace removeProperty(propKey) and removeProperty(propKey, propValue).

>#### .children()
>Get the children of each object in the set of matched objects, optionally filtered by a selector.
>````js
>$(element).children() // => collection of all children
>$(element).children(selector) // => collection of children that match the selector
>````
Working on views and folder requires a way to access children of an object. For views we'll have to decide what kind of proxy to return: is it a proxy for the underlying ArchiMate concept, or a proxy for the DiagramObject. In a perfect world, this should be a proxy for the DIagramObject but which also provide access transparently to the underlying ArchiMate concept (if any) so that .attr() return attributes from both (same for prop()...)?

>#### .find()
>Get the descendants of each object in the set of matched objects, optionally filtered by a selector.
>````js
>$(element).find() // => collection of all descendants
>$(element).find(selector) // => collection of descendants that match the selector
>````
This is complementary to .children().

**Comment by Phillipus** [comment]
> Only return concepts and view, but should return also the ArchimateModel itself and Folders.

Actually this is $() 

and fulfils:

> $() would return a collection with all concepts/views

(the star is internal.)

But we could have both.

**Comment by Phillipus** [comment]
Changed it:

$() - returns a collection with concepts and views for the current model
$("*") - returns a collection with concepts and views and folders for the current model

The model is already known from current model or from `model.$("*");`

**Comment by jbsarrodie** [comment]
jQuery uses $("*") (see [all selector](https://api.jquery.com/all-selector/)), so "\*" seems better... and works ;-)

*Reading you new comment*

Not sure we need both. Let me check the whole API, I'll certainly collect lots of remarks but we'll have to curate the list before any implementation change.

**Comment by jbsarrodie** [comment]
Implemented. Closing
