### ISSUE TITLE
.archimateConcept does not work for Relationships

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#10]
if one does 

$("view").each(function(view){
  var grouping_name = view.name + "__grouping";
  var theGrouping = $("grouping." + grouping_name).first();

  if ( theGrouping == null ) {
    theGrouping = model.addElement("grouping",view.name + "__grouping");
   }

  $(view).find('concept').each(function(child){
window.alert(child.type);
    model.addRelationship('aggregation-relationship','',theGrouping,child.archimateConcept);
  });

});

when It hits a relationship it fails....

**Comment by Phillipus** [comment]
~This code adds a grouping to the model, but not the view. Therefore it is not found in the view.~

**Comment by Phillipus** [comment]
Adding something to a view is not yet possible. Will be added soon.

**Comment by jbsarrodie** [comment]
My understanding of Ed'code is that for each views, it creates a sGrouping and makes this Grouping aggregate concepts that appear in the view.

Here it seems that calling `model.addRelationship()` with grouping and a relationship fails. This is in fact related to #15.

**Comment by Phillipus** [comment]
~Yes it fails because the code is trying to find it in the view, when it isn't in the view.~

~model.addRelationship by itself works.~

**Comment by jbsarrodie** [comment]
>Yes it fails because the code is trying to find it in the view, when it isn't in the view.

I don't understand: `model.addRelationship('aggregation-relationship','',theGrouping,child.archimateConcept);` tried to create an aggregate relationship from the Grouping and the underlying ArchiMate concept related to current view's concept (in each() loop).

I don't see where/why this code it is trying to find it in the view (butmaybe I need another coffee)

**Comment by Phillipus** [comment]
Yes, you're right. I was testing with a blank view.

I added one Business Actor to a view and ran the code. It works for me.

**Comment by Phillipus** [comment]
> when It hits a relationship it fails....

What does that mean?

**Comment by Phillipus** [comment]
I'm guessing at this point without full info. Perhaps trying to connect an aggregation relationship to another relationship?

**Comment by Phillipus** [comment]
Bear in mind that an exception is thrown if an invalid relationship is attempted between two concepts.

**Comment by Phillipus** [comment]
> Here it seems that calling model.addRelationship() with grouping and a relationship fails.

Works for me with aggregation relationships:

```
var actor = model.addElement("business-actor", "Oscar");
var role = model.addElement("business-role", "Cat");
var rel1 = model.addRelationship("assignment-relationship", "", actor, role);
var grouping = model.addElement("grouping", "Group");
var rel2 = model.addRelationship("aggregation-relationship", "", grouping, rel1);
```

(Edit, I meant aggregation)

**Comment by Phillipus** [comment]
Bug title is incorrect, .archimateConcept does work for Relationships. Something else is not happening per expectations.

**Comment by Phillipus** [comment]
BTW, better to use:

console.log(child.type);

than a window alert.

**Comment by Phillipus** [comment]
Tested this again now with a populated view. Works for me. Suggest providing a test case (model with the view) where it does not work

**Comment by gedwardroberts** [comment]
so I ran your code... and everything works except the last statement...

var rel2 = model.addRelationship("association-relationship", "", grouping,
rel1);


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
So what happens at that statement? Error message?

What version of Archi are you using? Have you edited the relationships.xml fiile or using the shipped one?

**Comment by Phillipus** [comment]
Should be:

var rel2 = model.addRelationship("aggregation-relationship", "", grouping, rel1);

**Comment by Phillipus** [comment]
Assuming you were using the wrong relationships.xml file, so closing this.
