### ISSUE TITLE
Automatically run script once element or relationship is created/updated

### ISSUE THREAD

**Issue by bbatbie-cmacgm** [archimatetool/archi-scripting-plugin#101]
Is there a hook/listener mechanism allowing to trigger a script once an element or a relationship is created/updated?

**Comment by Phillipus** [comment]
No. This is not implemented in jArchi.

**Comment by bbatbie-cmacgm** [comment]
Thank for quick-reply Phil!
Any chance to have it added in roadmap?

**Comment by olfway** [comment]
This issue is closed as completed but I didn't find any instructions. Does it really completed?

**Comment by Phillipus** [comment]
> This issue is closed as completed but I didn't find any instructions. Does it really completed?

No, there are no plans to implement it.
