### ISSUE TITLE
Typo in CONNECTION_TEXT_POSITION.options

### ISSUE THREAD

**Issue by lavenderb** [archimatetool/archi-scripting-plugin#105]
Just to note a simple spelling error in the fixed strings representing connection text positions
`CONNECION_TEXT_POSITION.SOURCE (value of 0)
CONNECION_TEXT_POSITION.MIDDLE (value of 1)
CONNECION_TEXT_POSITION.TARGET (value of 2)`

**Comment by Phillipus** [comment]
Thanks! Fixed in next version of jArchi and wiki updated.

**Comment by Phillipus** [comment]
Fixed in 1.2.1
