### ISSUE TITLE
[feature request] use of jarchi to change font direction

### ISSUE THREAD

**Issue by colin66south** [archimatetool/archi-scripting-plugin#107]
Would be useful to be able to change the font direction of any object from the default left to right, to up-down, or down-up for better visualisation of the view. If an angle were to be included, this would be even better.

Many other EA tools have this feature and is very useful for business stakeholder presentation.

**Comment by Phillipus** [comment]
A jArchi script can only perform a sub-set of actions that already exist in the main Archi code. Right now alternate text directions are not implemented in Archi so therefore this is not possible in jArchi. 

See https://forum.archimatetool.com/index.php?topic=1044
