### ISSUE TITLE
model, view, folders

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#11]
so there are the following

model   - ArchiMateModel
view      - ArchiMateDiagramModel
folder    - Folder

there is no documentation on how one gets its parts.... children does not work... there is nothing in the documentation about how to get to all of the parts

**Comment by jbsarrodie** [comment]
Parts are accessible through children() and find(). If it doesn't work then it's a bug.

**Comment by Phillipus** [comment]
As far as I can see children() works. But has to be called on a collection.

**Comment by jbsarrodie** [comment]
Yep, was so obvious to me that I didn't write it: all "navigation" is done on a collection, so you get view's childrens through $(view).children(). and so on
