### ISSUE TITLE
Feature request: Add window.promptSelection to Init.js

### ISSUE THREAD

**Issue by ThomasRohde** [archimatetool/archi-scripting-plugin#112]
I suggest to add a selection prompt to Init.js, prompting the user to select from a list of given string options. Suggested implementation in Init.js:

```
window.promptSelection = function (title, choices) {
    var ElementListSelectionDialog = Java.type('org.eclipse.ui.dialogs.ElementListSelectionDialog');
    var LabelProvider = Java.type('org.eclipse.jface.viewers.LabelProvider');
    var dialog = new ElementListSelectionDialog(shell, new LabelProvider());

    dialog.setElements(choices);
    dialog.setTitle(title);
    dialog.open();
    result = dialog.getResult();
    if (result) return new String(result);
    else return null;
}
```

**Comment by Phillipus** [comment]
Sure I could add it, or you could submit a Pull Request if you prefer?

**Comment by ThomasRohde** [comment]
Please do. I'm not familiar with the process :-)

**Comment by Phillipus** [comment]
OK, I added it with a small modification to return the first element.

**Comment by lavenderb** [comment]
The 'Prompt for a Selection' Dialogue doesn't render like the other Console Dialogues.
The 'Alert', 'Confirm' & 'Prompt' Dialogues declare the word 'Archi' next to the header icon and place the user message at the top of the grey area ( see examples on the left).
By this convention, the Selector Dialogue looks odd: 
The user message replaces 'Archi' in the header and offers an unnecessary grey area & free text field above the selection options (example on the right).
Would also be nice if the selection area height were in proportion to the number of options?

<img width="971" height="563" alt="Image" src="https://github.com/user-attachments/assets/b76b4a41-7343-4415-acfb-18303a1ac753" />

.

**Comment by Phillipus** [comment]
The title displayed is the title you pass it when using it:

```js
var selection = window.promptSelection("Choose selection", ["Option 1", "Option 2"] );
```

It's a custom Eclipse component so you could customise it - https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/eclipseui/org/eclipse/ui/dialogs/ElementListSelectionDialog.java

**Comment by Phillipus** [comment]
I don't want to change the existing `promptSelection` because that will break it for existing users. But, as with all things jArchi, you can create your own:

```js
window.promptSelection2 = function(message, choices) {
    var ElementListSelectionDialog = Java.type("org.eclipse.ui.dialogs.ElementListSelectionDialog");
    var LabelProvider = Java.type('org.eclipse.jface.viewers.LabelProvider');
    var dialog = new ElementListSelectionDialog(shell, new LabelProvider());

    dialog.setElements(choices);
    dialog.setTitle("Archi");
    dialog.setMessage(message);
    dialog.open();
    result = dialog.getFirstResult();
    return result ? new String(result) : null;
};

var selection = window.promptSelection2("Choose selection", ["Option 1", "Option 2"] );
```

**Comment by lavenderb** [comment]
Yes - I'm passing the correct text that I want to substitute for "Choose Selection" - my issue is more where this text appears.
I was expecting it to look more like this ...

<img width="510" height="224" alt="Image" src="https://github.com/user-attachments/assets/bc0ab694-8d94-479f-9d63-83b9a5d7b17a" />

If the current version is the true intent, no problem - I'll try customising as you suggest

**Comment by Phillipus** [comment]
Setting the message there makes more sense and I think that's what we should have done originally. Can you suggest a change that would keep backward compatibility in `init.js`?

**Comment by lavenderb** [comment]
I could only suggest setting a third (optional) parameter in the function call.
It could be used to switch between selection styles: a simple list (as current), a drop-down list, a set of radio buttons, a cylinder wheel, a date picker etc... ( many future expansion possibilities ;-) )
No third argument- and things remain as they are. :-)

**Comment by Phillipus** [comment]
Please open a PR with the JS code...
