### ISSUE TITLE
Error when running scripts "Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "engine" is null"

### ISSUE THREAD

**Issue by startsevsa** [archimatetool/archi-scripting-plugin#117]
### Version of Archi, Operating System
Windows 10, x64
Archi 5.01 
(on 4.10 everything worked well)

### Version of this plug-in
jArchi 0.8.0.202006231201
Nashorn ES5 or ES6 - doesn't matter

### Any other plug-ins installed?
coArchi 0.87

### Expected Behaviour
Run the script

### Actual Behaviour
Error "Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "engine" is null"
![image](https://user-images.githubusercontent.com/14212283/226611002-1ab28a6a-7d7b-4d94-89bd-59ff522f5dc9.png)

### Steps to Reproduce the Behaviour
1. run any script
2.
3.

**Comment by Phillipus** [comment]
I've moved this to the jArchi issue tracker.

Please provide more details of the jArchi plug-in you are using - the version, whether you are using GraalVM or Nashorn in Preferences.

**Comment by startsevsa** [comment]
> Please provide more details of the jArchi plug-in you are using - the version, whether you are using GraalVM or Nashorn in Preferences.
 I've updated the description

**Comment by Phillipus** [comment]
That version is very old and won't work with Archi 5. Please use the latest version of jArchi.
