### ISSUE TITLE
no remove

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#12]
There seems to be no way to remove anything from the model... at least it is not documented

**Comment by Phillipus** [comment]
It's been added to the documentation. Please check again.

**Comment by gedwardroberts** [comment]
this is for concepts... but what about model, view, and folder?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
Same. Use view.delete(), folder.delete(). Not implemented for model, as deleting a model means deleting a file.

**Comment by gedwardroberts** [comment]
to not leave it to deduction... can we put it explicitly in the
documentation?


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
Done
