### ISSUE TITLE
Archi opens MS IE when Browser.open  called, instead of any Chromium based like Edge or Chrome etc

### ISSUE THREAD

**Issue by RemeteAndras** [archimatetool/archi-scripting-plugin#120]
Version of jArchi, Operating System
Archi 5.0.2
JArchi 1.4.0
Windows 10 Enterprise
Windows Feature Experience Pack 1000.19041.1000.0

### About
As CoArchi doesn't support history, and Archi doesn't show element's ids, so its hard to use Git's own history.
I'm writing a JArchi script, to open the selected element on Bitbucket web page, to be able to check the history there quickly.

### Problem
I have an issue when displaying Bitbucket page, as Archi opens the URL page, but the page doesn't work correctly.

### Expected Behaviour
Archi should use an up to date browser (at least MS Edge), or lunch the system default browser (eg. Chrome) to display an url.

### Actual Behaviour
Archi uses MS IE that can not handle many web pages like Bitbucket

### Steps to Reproduce the Behaviour (with attached test files/script)
Even Github looks quite ugly in IE.
run this:
var browser = Browser.open("https://github.com/archimatetool/archi-scripting-plugin/issues", "my test window");

**Comment by Phillipus** [comment]
Did you check the setting in Archi's Preferences to use Edge as the Browser on Windows?

See page 156 of the User Guide https://www.archimatetool.com/downloads/archi/Archi%20User%20Guide.pdf

**Comment by RemeteAndras** [comment]
Thanks for the quick answer!

Unfortunately, I missed the  "Use MS Edge" preference in "General" preference tab.

I had only checked the System / WebBrowser settings: that is on "Use external browser" / "Default system web browser"  but it still use internal browser, even if I set to Chrome or Edge. 

 
The suggested setting works (but needed to  restart Archi to become effective)

Thanks

**Comment by Phillipus** [comment]
> I had only checked the System / WebBrowser settings: that is on "Use external browser" / "Default system web browser" but it still use internal browser, even if I set to Chrome or Edge.

The jArchi `Browser` only uses the internal browser.
