### ISSUE TITLE
[Feature Request] Support expanded label Expression retrieval via jArchi

### ISSUE THREAD

**Issue by RaimondB** [archimatetool/archi-scripting-plugin#123]
I am loving Archi and jArchi and am currently writing a script that needs to access label Expressions.

I found out that Label Expressions are supported since #115. (using .labelExpression)
However, it is not listed in the docs at the moment.

Also, I would like to be able to get the expanded label expression as well, so that I can use the end result of its processing.
Or maybe this is available as wel an I just don't know how to do it? ;-)

Note: I also like the idea of setting the label expression, so we should have access to the raw Version as well.
Maybe something like .getLabel() ?

**Comment by Phillipus** [comment]
Hi, this is implemented and documented. See https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-Object#labelexpression and https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-Object#labelvalue

**Comment by RaimondB** [comment]
Hi @Phillipus , this is great :-) . I did not find it because I was looking here for the docs:
https://jarchi-api.readthedocs.io/en/latest/jArchi-Object/

I see there is mentioning on some pages that this is deprecated, but I thought it was only about part of the docs.
Also, it still really ranks high in Google.

I'll bookmark the new location.

**Comment by jbsarrodie** [comment]
> Hi @Phillipus , this is great :-) . I did not find it because I was looking here for the docs: https://jarchi-api.readthedocs.io/en/latest/jArchi-Object/

Oops, it seems I tested readthedocs some years ago and totally forgot about it. I'll delete it asap.
