### ISSUE TITLE
diagram-model-note imageSource returns always -1 even with a custom image

### ISSUE THREAD

**Issue by romualdrichard** [archimatetool/archi-scripting-plugin#124]
JArchi 1.5
I use Export Folder New Model script and I found that all my notes with images are not exported.
Digging the script, it seems that objetc diagram-model-note always returns -1 with diagram-model-note.imageSource

### Expected Behaviour
return IMAGE_SOURCE.CUSTOM

**Comment by Phillipus** [comment]
Can you please point me at the script you are using?

Edit: I will investigate...

**Comment by Phillipus** [comment]
`imageSource` only applies to ArchiMate elements. Notes and Groups do not have this attribute. So for a Note, ignore this attribute and get the Image Path from `getImage().path`

I've updated the wiki to make this clear.

**Comment by romualdrichard** [comment]
Yes,
Script from [Export Selected Folder to New Model.ajs](https://gist.github.com/fanievh/4ec7d14247616846f3d16b5e22dc80a9)

**Comment by Phillipus** [comment]
Thanks for the link. It seems that the script does not handle the images for Notes properly. I didn't have time to fully debug the script but I got it to work by removing line 510 and the closing bracket on line 523:

`if (sourceObject.imageSource === IMAGE_SOURCE.CUSTOM) {`

**Comment by romualdrichard** [comment]
I changd it to   if ((sourceObject.imageSource === IMAGE_SOURCE.CUSTOM ) || (sourceObject.getImage().path)) and that do the trick

**Comment by Phillipus** [comment]
OK, so let's close this.
