### ISSUE TITLE
junction is instantiated through element

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#13]
junction is instantiated through element ... but this is not in the documentation

**Comment by Phillipus** [comment]
It is in the documentation now.

**Comment by gedwardroberts** [comment]
would there be a way to remove junction from the relationship column in the
table and put it in the Relationship Connector column?... the fact that you
use Element on it is a lot farther down in the documentation... might need
a note underneath the table just so there is no confusion...

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by jbsarrodie** [comment]
I've moved it to the 'Other' columns (I'd like to avoid creating another column just for junction.
