### ISSUE TITLE
deriveLineColor and lineColor does not work for an element

### ISSUE THREAD

**Issue by Sonique** [archimatetool/archi-scripting-plugin#134]
### Version of jArchi, Operating System
5.3.0 mac silicon 

### Expected Behaviour
Script will change line color and line weight
### Actual Behaviour
Script works and change other element properties, but line color and width are unchanged 

### Steps to Reproduce the Behaviour (with attached test files/script)
1. create single element
2. run script with line color change
3. it doesn't works

```
var elements = $(selection)
$(elements).each(function (element) {
    console.log("Setup appearance");
    // Fill color
    element.fillColor = "#D6E8D5" // New element
    // Line color
    element.deriveLineColor = false;
    element.lineColor = "#F00000"; // Modified element
    element.lineWidth = 3;
}
....
``
`

**Comment by Phillipus** [comment]
Hi, I tested the followings script after selecting some elements in a View and it is working OK:

```js
$(selection).each(function (element) {
    element.fillColor = "#D6E8D5"
    element.deriveLineColor = false;
    element.lineColor = "#F00000";
    element.lineWidth = 3;
})
```

Don't forget to select the element in the View first.

**Comment by Phillipus** [comment]
Which version of jArchi are you using?

**Comment by Sonique** [comment]
jarchi 1.5.0.202310011312

it's strange, but on my side script doesn't work for line color. I tested on new project, same thing. Yes, I did select element. Color changed, but element border color doesn't

**Comment by Phillipus** [comment]
> jarchi 1.5.0.202310011312

These features were added in jArchi 1.6. Please see https://github.com/archimatetool/archi-scripting-plugin/wiki/Change-Log

**Comment by Sonique** [comment]
https://github.com/archimatetool/archi-scripting-plugin/assets/662904/b6f0497a-ea9c-45df-b9dc-754dd0de153c

**Comment by Sonique** [comment]
Oh, well. Looks like I missed it on patreon. Will download new version. Thanks
