### ISSUE TITLE
[Feature Request] Document how to work with rich text (if possible) in the Element.documentation

### ISSUE THREAD

**Issue by RaimondB** [archimatetool/archi-scripting-plugin#135]
### Description

I am using jArchi to automatically import documentation that is HTML formatted. It is unclear to me in what way I can encode the text to show it in the same way as the HTML.
E.g. Show links, have bullet points etc.

What is the format that the documentation field is expecting, because I do see it is possible to put hyperlinks in there.

If no formatting is currently possible, the feature request is to make this possible with either markdown or HTML.

**Comment by Phillipus** [comment]
Hi, the Documentation field only supports plain text. Only hyperlinks are rendered.

> If no formatting is currently possible, the feature request is to make this possible with either markdown or HTML.

Please see https://github.com/archimatetool/archi/issues/1032
