### ISSUE TITLE
[Feature Request] Python scripting support with GraalPy

### ISSUE THREAD

**Issue by dpelevin** [archimatetool/archi-scripting-plugin#138]
### Description

As first stable release of GraalPy [is ready](https://medium.com/graalvm/whats-new-in-graal-languages-24-1-b2452c9debae) it would be nice to have an option to use Python as a Archi Scripting Plug-in scripting language.

**Comment by Phillipus** [comment]
Hi, jArchi is really designed to be used with the JavaScript language syntax so I won't be implementing GraalPy or supporting it. However, if you wish to create your own implementation as a plug-in please go ahead.

**Comment by dpelevin** [comment]
@Phillipus
Isn't GraalJS and GraalPy both have the same scripting interface that abstracts from the implementation of the specific scripting language?

**Comment by Phillipus** [comment]
> @Phillipus Isn't GraalJS and GraalPy both have the same scripting interface that abstracts from the implementation of the specific scripting language?

I guess so. But as I said, I won't be implementing it as I have too much other stuff to do. That's why this project is open source and extendible through plug-ins so that other people can implement their own requirements.

**Comment by dpelevin** [comment]
> > @Phillipus Isn't GraalJS and GraalPy both have the same scripting interface that abstracts from the implementation of the specific scripting language?
> 
> I guess so. But as I said, I won't be implementing it as I have too much other stuff to do. That's why this project is open source and extendible through plug-ins so that other people can implement their own requirements.

I've got your reasoning. I just confirming that the reason feature request is rejected was not technical or architectural limitations of the Archi Scripting Plug-in. Now I have the desired confirmation, thanks.
