### ISSUE TITLE
javax.script.ScriptException: java.lang.IllegalArgumentException: Argument not valid

### ISSUE THREAD

**Issue by MarekDinka** [archimatetool/archi-scripting-plugin#139]
### jArchi Version

1.6.1

### Archi Version

5.3.0

### Operating System

Ubuntu 22.04.5 running as WSL on Windows 10

### Description

Hi, I am running into this exception when trying to export view as a png file using jArchi. I am doing this by running the `export.ajs` script (see Files.zip) on a model which I have generated using other jArchi scripts (see Files.zip for the model)
[Files.zip](https://github.com/user-attachments/files/17945531/Files.zip)

Console:
```
$ Archi -application com.archimatetool.commandline.app -consoleLog -nosplash --loadModel "model.archimate" --script.runScript "export.ajs"
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
[Core] Loaded model: 'Model'
javax.script.ScriptException: java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:4899)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:428)
        at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:287)
```

Note: This view can be exported by using the normal archi's buttons

**Comment by Phillipus** [comment]
Hi, the View in your example model contains one object with an `x` co-ordinate of `56065`:

```
<child xsi:type="archimate:DiagramObject" id="id-de1e6fbad58844bfa3020dd4b9fccc5d" archimateElement="06938d5cee7464cf7dfe3f4da6edff558a87358b">
  <bounds x="56065" y="20" width="120" height="55"/>
</child>
```

This will create an image that is probably consuming too much memory, hence the crash. Move that object back into a reasonable position either in Archi or edit the .archimate file manually in a text editor to adjust that x position.

**Comment by Phillipus** [comment]
BTW, you can use:

```
$.model.renderViewToFile(view, "filename", "PNG", {scale: 1, margin: 20});
```

See https://github.com/archimatetool/archi-scripting-plugin/wiki/Model-Functions#renderViewToFile

**Comment by MarekDinka** [comment]
I see, moving it resolves this. I suspected it might be something like this, but the error message had me confused, thank you.
