### ISSUE TITLE
no way to create new folder

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#14]
there seems to be no way to add in a new folder...  needs to be added into the types one can instantiate

**Comment by Phillipus** [comment]
Will be added in a later release.

**Comment by Phillipus** [comment]
@jbsarrodie 

What API would be best for this?

- A folder always has a parent folder, so it could be a method of FolderProxy.
- Or it could be a method of ArchimateModelProxy (like addRelationship and addElement)

**Comment by jbsarrodie** [comment]
My 2cts on this:
- My feeling is that .addFolder(name) should be a method of FolderProxy. Seems the most logical to me.
- We should then add a method to move a concept in a specific folder. This could be done from the FolderProxy (through a .add(concept) method) or from the ArchimateConceptProxy (through getFolder() / setFolder(folder) method) or both
- On ArchimateModelProxy, .addElement() and .addRelationship might be renamed to .createElement() and .createRelationship(). They could also be extended to support a folder as argument in which the concept will be put.

**Comment by gedwardroberts** [comment]
Do you allow a concept to be in two different folders at once or only in
one?... exchange format allows multiple folders....

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
One instance only.

**Comment by jbsarrodie** [comment]
In Archi a concept is in only one folder. So adding a concept to a folder automatically removes it from previous folder. In addition we have rules that states that a business element is only inside a subfolder of "Business" folder, etc...

**Comment by Phillipus** [comment]
To be clear - the only issue here is to how add a folder, and how to add/move elements to it. Discussions of the exchange format and whether one instance is right or wrong is out of scope.

**Comment by Phillipus** [comment]
- added FolderProxy#createFolder(name)
- added FolderProxy#add(concept)
- ArchimateModelProxy#addElement() renamed to createElement()
- ArchimateModelProxy#addRelationship() renamed to  createRelationshipt()
- Optional parent folder parameter added to  createElement() and  createRelationship()
- Unit tests applied

**Comment by jbsarrodie** [comment]
You rock !

**Comment by Phillipus** [comment]
Closing this. If there is a problem with this new API (available in next build) please open new issues

**Comment by gedwardroberts** [comment]
How do I get the next build?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
> How do I get the next build?

Same method as last time. Will be next week some time.
