### ISSUE TITLE
addRelationship will not work with a Relationship

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#15]
there are multiple relationships to relationships.... any relationship can be a source or target to a (association) relationship to an Element (but not a relationships to relationship)... 

also Product, Grouping, and Location can have aggregation and composition to a relationship.... but that does not work,... and it is not documented this way either...

**Comment by Phillipus** [comment]
Works for me.

```
var actor = model.addElement("business-actor", "Oscar");
var actor2 = model.addElement("business-actor", "Oscar2");
var role = model.addElement("business-role", "Cat");
var rel1 = model.addRelationship("assignment-relationship", "", actor, role);
var rel2 = model.addRelationship("assignment-relationship", "", actor2, role);
var rel3 = model.addRelationship("association-relationship", "", rel1, actor2);
```

**Comment by Phillipus** [comment]
Please supply a test case where this does not work.

**Comment by gedwardroberts** [comment]
so if you use Archi... you can't connect a Grouping to a relationship
through an aggregation... so I don't think Archi supports this... but this
is
allowed in ArchiMate 3.0.1

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
Yes you can do this in Archi 4.2.

Again - please supply a test case where this does not work.

**Comment by Phillipus** [comment]
![screen shot 2018-07-13 at 06 00 03](https://user-images.githubusercontent.com/600504/42673204-13e153b2-8662-11e8-8d3f-3c17e340372e.png)

**Comment by gedwardroberts** [comment]
yes... it was the relationship.xml file... I was using the new one for 3.1
.. so now I need to go and debug that one...

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by gedwardroberts** [comment]
the difference between the files is that the current relationship.xml has
no relationship information... and the new .xml has relationship
information...

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com
