### ISSUE TITLE
$(view).each

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#17]
to get to the elements in view one used $(view).each(function(concept){...});

but this does not work with Folders

**Comment by jbsarrodie** [comment]
_Editing now that I have drink my coffe_

$(view) will return a collection that contains only the view passed as argument. Then .each() will iterate on the collection members, thus your function will be called only once with the view (and not its content) as argument.

**Comment by Phillipus** [comment]
If you select a folder in the tree then the following snippet returns the concepts in that folder:

```
selection.children().each(function(child){
  console.log(child);
});
```

**Comment by gedwardroberts** [comment]
here is the code I was running...

$("view").each(function(view){
  var grouping_name = view.name + "__grouping";
  var theGrouping = $("grouping." + grouping_name).first();
  if ( theGrouping == null ) {
    theGrouping = model.addElement("grouping",view.name + "__grouping");
   }
  view.children().find('concept').each(function(item){
console.log(item.concept.type + " : " + item.concept.name);

model.addRelationship('aggregation-relationship','',theGrouping,item.concept);
  });
});


$(view).find('concept')....   works

view.children().find('concept') does not... it gives me an error

according to what you said I should be able to get the collection using
children... and that $(view) means nothing... but that is not what
I am experiencing...

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
`view` is not a collection so `view.children()` is not a valid function. Using `$(view)` wraps view in a collection and so use `$(view).children()`

This does not relate to original post of "but this does not work with Folders" so closing this.

**Comment by gedwardroberts** [comment]
this is what is so confusing... why isn't it a collection?... logically it
is a collection of Visual Objects?... what does wrapping it in $() do...
and why does it magically then make it a collection... and what about
model, folder as well?... are they the same way?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by gedwardroberts** [comment]
and one other question... how would I have known that from the
documentation?...

does model.find('view') give me a collection of views?... I am missing an
overall concept of how this is all put together... is there a diagram that
shows how it is put together?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by jbsarrodie** [comment]
OK, doc on wiki needs some improvements :-)

Don't know if this will help you but this is borrowed from jQuery. So same basic principles apply here.

So in jArchi there is a clear distinction between objects (can be archimate concepts, folder, view, visual objects...) and collection of objects. Most API features (like navigation) are through collections, so the first thing to do is to create a collection through `$()` which takes as input:
- a selector (string) and then returns object matching the selector
- a collection and then simply returns it (useful in some cases)
- an object and then returns a collection containing it (thus with only one member)
