### ISSUE TITLE
tie the scripting into being adapter for EMF 

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#19]
Request: tie the scripting into being adapter for EMF ... so when things like add, remove, changes happen one can tie scripting code into it

**Comment by Phillipus** [comment]
Interesting idea. Perhaps something for a future version.

**Comment by gedwardroberts** [comment]
this is a game changer...


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com
