### ISSUE TITLE
Invoke script through context menu

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#2]
For the moment the plugin works only using the whooe model as a starting point. Several use cases (eg. extract information for a set of views) require a way to run a script with a kind of "selection".

I suggest we add a way to select concepts and views on the model tree and run a script from a context menu. This selection could then be made available to script through a pre-defined exposed variable (list of EObject or something similar).

**Comment by Phillipus** [comment]
Implemented. Can be modified if required.

**Comment by jbsarrodie** [comment]
This works as expected. Closing
