### ISSUE TITLE
can one import other javascript files into a javascript file

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#20]
can one import other javascript files into a javascript file... if so can we document what you have allowed for that...

**Comment by jbsarrodie** [comment]
Yes, you can `load()` other scripts:
- `load(absolute_path)`
- `load(url)`

There is no built-in relative load, but you can do it through `load(__DIR__ + relative_path)`.

`__DIR__` contains the absolute path of the folder in which current script is.
`__FILE__` contains absolute path of current script.
`__LINE__` contains the line number in which `__LINE__` is used.

**Comment by gedwardroberts** [comment]
can this go into the documentation?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by Phillipus** [comment]
Done.

https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-API-Documentation#including-other-script-files
