### ISSUE TITLE
suggestion rename is() to isType()

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#22]
suggestion rename is() to isType()... is() can be misleading...

**Comment by jbsarrodie** [comment]
Won't do that because:
- is() can use any selector thus Type is just one use-case among others
- is() is created this way in [jQuery](https://api.jquery.com/is/) and we stick to jQuery conventions/api whenever possible.

**Comment by gedwardroberts** [comment]
ok... so what is the syntax of a selector then... since it is not CSS...

type [<attribute-name>=<attribute-value>] ?

ed


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by jbsarrodie** [comment]
All supported selectors are documented [here](https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-API-Documentation#selectors).

Maybe you should provide more details for your use-case.

But if you want to filter objects based on some attributes, you have to use [filter(function)](https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-API-Documentation#filter) and pass a function checking those attributes.
