### ISSUE TITLE
add in specific syntax and examples for visual objects

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#23]
the visual object attributes... like fillColor... what is the syntax here for giving a value... 

needs to be in documentation and perhaps an example...

**Comment by jbsarrodie** [comment]
Syntax is similar to css: "#rrggbb". Wiki has just been updated (under Visual Object).

**Comment by gedwardroberts** [comment]
Did this go into the api doc?

**Comment by jbsarrodie** [comment]
Yes ;-)

>Wiki has just been updated (under Visual Object).

**Comment by Phillipus** [comment]
Good, then we can close this issue. ;-)

BTW - wiki will be much improved over the coming days.
