### ISSUE TITLE
which types can be created... 

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#24]
model.addElement('archimate-diagram-model','');

does not work... this brings up which things you can create and which you can't... needs to be in the documentation...

I do think that it should be called createElement rather than addElement

**Comment by jbsarrodie** [comment]
>does not work... this brings up which things you can create and which you can't... needs to be in the documentation...

Agree. I'm adding it to my todo list

>I do think that it should be called createElement rather than addElement

Agree.

See #26

**Comment by Phillipus** [comment]
Quick response:

In my experience...

`createXXX()` usually suggests that something is created and returned, but _not necessarily_ added to the data model (see the `IArchiMateFactory.eInstance.createXXX()` methods)

`addXXX()` usually suggests that something is both created and added to model (and returned).

**Comment by jbsarrodie** [comment]
This is true for a factory ( and woujld be true also for $.model.createXXX), but as in this case createXXX() would be called from a model, I think it suggests that it is created and added to the model.

I'd like to keep .addXXX() for some future use-cases where concepts will be created outside the model (or coming from another model).

**Comment by Phillipus** [comment]
Changed to createXXX();
