### ISSUE TITLE
Diagram component class type selectors are not implemented

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#25]
In the [wiki ](https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-Collection#object-selector-type)we say that these visual class types are supported:

```
diagram-model-note 
diagram-model-group 
diagram-model-connection
diagram-model-image
diagram-model-reference
sketch-model-sticky
sketch-model-actor
canvas-model-block
canvas-model-sticky
canvas-model-image
```

Using any of these to select or filter a collection does not currently work. This is because `SelectorFilterFactory` does not check if these types are instances of `IDiagramModelComponent`. Currently, the only type instanceof checks are on:

```
IArchimateConcept
IDiagramModel
IFolder
```

We need to add `IDiagramModelComponent` to these for this to work.

**Comment by jbsarrodie** [comment]
I have to think a bit more about it...

**Comment by Phillipus** [comment]
...did you have a think? :-)

**Comment by jbsarrodie** [comment]
> ...did you have a think? :-)

Yes ;-)

I think there are several small things to fix. Basically the idea is to have:
1. All selectors but `"#id"` called on the **model** should return only Concepts, Views and/or Folders,
2. All selectors but `"#id"` called on a **Collection** should return any object for which the underlying ArchiMate concept matches
3. `"#id"` should check on the object (not underlying ArchiMate concept)

This leads me to these changes (not tested, just mental coding):
- In **ArchimateModelProxy**, `find(String)` should be updated to add the `find("*")` only when `selector` is different from `"#id"`. BTW, from a performance point of view, we should do the filtering on `"*"` after the filtering on `selector`.
- In **SelectorFilterFactory**, both _Find all objects with given type and name_ and _Class type of concept_ should have the the `instanceof` conditions removed.

**Comment by Phillipus** [comment]
> BTW, from a performance point of view, we should do the filtering on "*" after the filtering on selector.

We have this now:

```
    public EObjectProxyCollection find(String selector) {
        return super.find("*").filter(selector); //$NON-NLS-1$
    }
```

So that means:

1. Get a collection ("*")
2. Filter on that collection

Because filter() only works on a collection we still need to get a collection first, so how would we do that?

What we have now is equivalent to:

`find().filter("*").filter(selector);`

We could do it this way:

`find().filter(selector).filter("*");`

**Comment by jbsarrodie** [comment]
We should do find(selector).filter(*) (but the last filtrer should not be done for #)

**Comment by Phillipus** [comment]
OK, that is the equivalent of `find().filter(selector).filter("*");`

**Comment by Phillipus** [comment]
~New branch "selector-change" pushed.~
(Edit: now in "master" branch)

I think @jbsarrodie 's "mental coding" was correct. :-)

Please test when you have a moment.

**Comment by Phillipus** [comment]
> BTW, from a performance point of view...

Well, that got me looking at the overall performance of the `find()` and `filter()` methods in `EObjectProxyCollection` and these can be very slow indeed.

The bottleneck is checking for uniqueness when adding an object to `EObjectProxyCollection` (which is actually an `ArrayList`). The call to `list.contains(object)` to check first if the list contains the object is incredibly slow.

We had the same problem when we fixed the slowness of opening models when IDs were being checked against a list.

So...

in the methods that add objects to an `EObjectProxyCollection` we now use a temporary `LinkedHashSet`, which is a _Fantastillion_ times faster than an `ArrayList`.

~These changes are also in the "selector-change" branch.~
(Edit: now in "master" branch)

**Comment by Phillipus** [comment]
These changes have been merged to "master" branch now.
