### ISSUE TITLE
getType() returns camel case class type instead of kebab-case

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#27]
Presently calling getType on an object returns the type class as camel case:

````
var type = $('business-role').first().type;
console.log(type);
````

returns `"BusinessRole"`

So, if we wanted to test a type against a string we have to use camel case instead of kebab-case.

Should we return type as kebab-case?

**Comment by jbsarrodie** [comment]
I noticed this tooo.

We have to be consistent, so we should return type as kebab-case.

**Comment by Phillipus** [comment]
Done.
