### ISSUE TITLE
Re-organise wiki

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#28]
The wiki API page is getting rather long. Suggest breaking it up into sections.

Agree? Disagree? Suggestions?

**Comment by jbsarrodie** [comment]
Yep, agree.

I was starting to provide guidelines here but it certainly is quicker to do it now and let you fix some broken links :-)

I will update this issue when done

**Comment by Phillipus** [comment]
Not sure what you mean ;-) but I'm happy to edit the wiki(s) if we can agree a structure. Perhaps something like:

- API
  - Collection
  - Objects
  - Adding and Creating
  - Prompt, Alert and File Dialogs

**Comment by jbsarrodie** [comment]
Done, I've splitted API Documentation across sub pages, updated the Home and added a sidebar (same content as Home's TOC).

Is it better now?

**Comment by Phillipus** [comment]
OK, thanks. I'll give it a review soon and add more content.

The next build of jArchi will require some changes and additions, and I'll do those too.
