### ISSUE TITLE
Which object methods should be public?

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#29]
These are currently public methods:

```js
ArchimateConceptProxy#inRels()
ArchimateConceptProxy#outRels()
ArchimateConceptProxy#objectRefs()
ArchimateConceptProxy#viewRefs()

DiagramModelProxy#objectRefs()
DiagramModelProxy#viewRefs()
```

Should they remain public or only accessed via `EObjectProxyCollection`?

**Comment by Phillipus** [comment]
I just remembered why these methods are declared public. It's because we have used Java interfaces:

```
IConnectableProxy
IReferencedProxy
```

so the implementing methods have to be public.

So the question is no longer valid. The issue is that we agree that these are not public API?

**Comment by Phillipus** [comment]
I've just devised a cunning way to internalise these Java interfaces so that the methods above are not public. :-)

Are we agreed that these methods should not be public API?

```js
ArchimateConceptProxy#inRels()
ArchimateConceptProxy#outRels()
ArchimateConceptProxy#objectRefs()
ArchimateConceptProxy#viewRefs()

DiagramModelProxy#objectRefs()
DiagramModelProxy#viewRefs()
```

**Comment by jbsarrodie** [comment]
Yes, they should be private or protected.

**Comment by Phillipus** [comment]
Thanks. Changes pushed. :-)
