### ISSUE TITLE
Relationship isLegal

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#30]
need the ability to see if a relationship is legal perhaps before you try to build it... 

so 

isLegal(relationship,source-type,target-type)

**Comment by Phillipus** [comment]
Yes, this seems a good idea since creating a relationship will throw an exception if it's not valid.

I propose:

```js
$.model.isAllowedRelationship(relationshipType, sourceType, targetType);
```

Example:

```js
var isValid = $.model.isAllowedRelationship("influence-relationship", "business-actor", "business-role"); // returns false
```

Open to suggestions for a different method name, but it should make the method's purpose clear.

**Comment by jbsarrodie** [comment]
This seems perfect :-)

**Comment by Phillipus** [comment]
Done. Committed to master for next build.
