### ISSUE TITLE
Setting the opacity of Application-Interface elements does not work

### ISSUE THREAD

**Issue by rfamans** [archimatetool/archi-scripting-plugin#35]
### Version of jArchi, Operating System
Archi 4.3 on windows 10

### Expected Behaviour
I have below script that (among others)  should set the opacity of an Application-Interface element,

        element.fontSize  = "10";
        element.fontColor = "#545556";
        element.fontName  = "Arial Narrow";    
        element.opacity = "0";  

### Actual Behaviour
When I run this code, all element appearance attributes are set according to the script except from the opacity attribute which is not set according to script.

### Steps to Reproduce the Behaviour (with attached test files/script)
1. Create interface element in a view
2. give it a background color and a line color (all colors except white are fine). 
3. run my script snippet and see that the interface element does not receive the expected opacity setting

**Comment by Phillipus** [comment]
Are you saying that opacity is not set only for Application-Interface elements or for all elements?

Which version of jArchi do you have? The latest is com.archimatetool.script_0.4.1.201810261941 and opacity was added to that version.

If you need the latest version, it's available in a Patreon post or the link I sent you if you donated by PayPal.

**Comment by rfamans** [comment]
In my case, it didn't work for application-interface elements but it could also not be working for other types of elements.

I donated and I am currently on version: 0.4.0.201808090947. Since august 9th, I did not receive update notifications for newer versions.

**Comment by Phillipus** [comment]
You need version com.archimatetool.script_0.4.1.201810261941 - send me an email for the update.

**Comment by rfamans** [comment]
com.archimatetool.script_0.4.1.201810261941 has solved the issue
