### ISSUE TITLE
.find() does not work as expected for diagram objects

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#36]
Hi,

It seems that when working on diagram objects, .find() almost always return a bad value (or zero). .children() works as expected though.

The main difference between both is that .children() relies on class specific implimentation while .find() is hard coded to use getEObject().eAllContents() which doesn't seem to work for diagram objects.

**Comment by Phillipus** [comment]
Perhaps .find() needs to be implemented for each proxy class? If so, how does it differ functionally from .children()?

**Comment by jbsarrodie** [comment]
In fact, I think that .find() implementation shoujld be based on .children(). At the end we just create a big collection containing children and children's chidren...

I will try to provide a patch soon.

**Comment by Phillipus** [comment]
Testing with nested diagram objects and selecting the parent object, `.find()` is returning the child objects for me.

`console.log(selection.find());`

What am I missing?

**Comment by Phillipus** [comment]
`find` also includes nested relationships, where `children` does not.

**Comment by jbsarrodie** [comment]
> `find` also includes nested relationships, where `children` does not.

Ok, that's the root cause of my issue. This should not be the case as in fact a relationship is neither inside its source nor its end, it just **is**. But because of the way it is managed in EMF model, they get added by `eAllContents()`.

So a simple workaround for me ATM is to use .find("element"). We'll have to decide how to fix it in the code, but we could basically do the same, that is: keep the code as is but simply add a filter("element") before returning the result.

**Comment by Phillipus** [comment]
But there is a difference between `children` and `find`. Generally,  `children` returns immediate child objects (except for a View `children()` returns immediate child objects and relationships). Whereas in all cases `find` is digging in all the way down with `eAllContents()`. i.e "everything all the way down". If we change the behaviour of find for a DiagramObject then it no longer follows that rule, but is really a `children` function.

**Comment by jbsarrodie** [comment]
No because we have to return children's childen (and so on) in any case. The key point is that relationships are not children of objects but only of the whole diagram.

But my initial suggestion actually doesn't work as in fact we would have to check if find() is being called on a diagram object before filtering.

**Comment by Phillipus** [comment]
> But my initial suggestion actually doesn't work as in fact we would have to check if find() is being called on a diagram object before filtering.

We just implement and over-ride `find` in `DiagramModelObjectProxy`

**Comment by Phillipus** [comment]
Maybe we accept that find does a deep collection of "everything" and that's its role, but in practice use a selector. Functionally, `find` (as it is) is needed so we can filter on it.

> We just implement and over-ride find in DiagramModelObjectProxy

Perhaps not because filtering for relationships won't work.

**Comment by jbsarrodie** [comment]
The root issue is that we in fact have different notions of parents hierarchy deoending on whether we use children or find.find should really be equivalent to getting children's children, but in our case it is not because children never returns relationships on diagram objects while find does.

IMHO relationships should be children of the diagram, not of their source element. 

So:
* children called on a diagram should return first level elements and all relationship
* find called on a diagram shoukd return all elements and relationships 
* find called on an element should return only elements that are children and children's children...

**Comment by Phillipus** [comment]
~Ok. But as we are using find() to get everything we should make that implementation private and use it as needed.~

Not needed.

**Comment by Phillipus** [comment]
I tested this in `DiagramModelObjectProxy`:

```
@Override
protected EObjectProxyCollection find() {
    EObjectProxyCollection all = super.find();
    return all.filter("element");
}
```

Seems to work.

**Comment by jbsarrodie** [comment]
>Ok. But as we are using find() to get everything we should make that implementation private and use it as needed.

If by "that implementation" you speak about the fixed one I suggest, then, no because if somewhere in the code we rely on find(), then we expect the right behavior. To be clear, find() behavior oudside the context of diagram is good, the only issue is with diagrams because we used the internal EMF representation of a diagram and its elements to support find(), but we should have used a more "logical" way at seeing at diagram.

**Comment by Phillipus** [comment]
Yep. I see that now. The code in comment above seems to do it.

**Comment by jbsarrodie** [comment]
> I tested this in `DiagramModelObjectProxy`:
> 
> ```
> @Override
>  protected EObjectProxyCollection find() {
>      EObjectProxyCollection all = super.find();
>      return all.filter("element");
>  }
> ```
> Seems to work.

Good. I wonder if this impacts only `DiagramModelObjectProxy`... In theory this should also impact notes and connections (I suppose that calling find() on a note returns connextions...).

In fact, we should filter for every `DiagramSomething` that is not the diagram itself.

**Comment by Phillipus** [comment]
As we don't call find() recursively on children it should only affect `DiagramModelObjectProxy` and `DiagramModelNoteProxy`.

> In fact, we should filter for every DiagramSomething that is not the diagram itself.

Including `DiagramModelConnectionProxy` ? Right now find() will return attached connections.

**Comment by Phillipus** [comment]
If we want same behaviour for connections that find() method can be moved to `DiagramModelComponentProxy`

**Comment by jbsarrodie** [comment]
> Including `DiagramModelConnectionProxy` ? Right now find() will return attached connections.

So it shouldn't. 

>If we want same behaviour for connections that find() method can be moved to `DiagramModelComponentProxy`

We do want

**Comment by Phillipus** [comment]
So, really DiagramModelConnectionProxy#find() should always return an empty collection?

**Comment by jbsarrodie** [comment]
> So, really DiagramModelConnectionProxy#find() should always return an empty collection?

Yes, a connection or relationship cannot have children so quite logically find() can't return anything.

**Comment by Phillipus** [comment]
OK, so I can change the code in two places:

DiagramModelConnectionProxy#find returns an empty collection
DiagramModelObjectProxy#find returns only elements

**Comment by Phillipus** [comment]
I've committed the changed code for this, if you'd like to test this at some point.
