### ISSUE TITLE
Feature request: export views to more than PNG format

### ISSUE THREAD

**Issue by timhale7** [archimatetool/archi-scripting-plugin#37]
I have a publication use case for this feature. I have a model with 19 views. I commonly publish the models to pdf for distribution. I use the File/Export/View as Image function to produce the PDFs. Executing this 19 times for each publication cycle takes a bit of time that I'd like to automate.

I'm told that jarchi can already programmatically manipulate and save views as PNGs. But I am left with the manual task of printing to PDF - so no real time savings or accuracy improvements there.

Consider adding ability to export views to more than PNG format in jArchi

Thanks

**Comment by Phillipus** [comment]
Close this as export to SVG / PDF will be in the next version of jArchi.

**Comment by timhale7** [comment]
Thank you
