### ISSUE TITLE
BUG - Don't show hidden (dotted) folders & files in Script Manager browser

### ISSUE THREAD

**Issue by GuyWicks** [archimatetool/archi-scripting-plugin#38]
### Version of jArchi, Operating System
Archi 4.3.1
OSX 10.14.2 (Mojave)

### Expected Behaviour
Folders and files that are usually hidden by the operating system (i.e. with dotted names) are shown in the Script Manager browser

### Actual Behaviour
If, for example, you use git to co-ordinate your scripts across teams and laptops, you will see a ".git" folder in the Script Manager.  The .git folder should not be seen. 

(Impact minor)

Note:
Behaviour only tested on OSX, not on Windows based.  (If I get a chance, I'll update this ticket with the Windows behaviour) 

### Steps to Reproduce the Behaviour (with attached test files/script)
1. Point Script Manager folder to a folder that had a .git folder
2. Open Script Manager browser
3. Observe the (usually hidden) .git folder in the tree

![image](https://user-images.githubusercontent.com/12052236/52175852-13b00a00-27a2-11e9-8db4-5be051198b49.png)

**Comment by GuyWicks** [comment]
Additional info: jArchi 0.4.1

**Comment by Phillipus** [comment]
Good point.

Fixed. Will be in next version.

:-)

**Comment by Phillipus** [comment]
Fixed in 0.4.3
