### ISSUE TITLE
Feature Request: Extend jArchi interface to allow access to 'Archi preferences'

### ISSUE THREAD

**Issue by GuyWicks** [archimatetool/archi-scripting-plugin#40]
Do you think it would be useful to be able to access the Archi preferences from jArchi?

$("preferences").find("preference name").get()   ???  .list .   .set ???

There are a few in particular I think could be useful:   The grid sizing and default object size would be useful for any script that wanted to do layout adjustment and not be hard coded.

(I'm working on a script that can "grid layout" a series of concepts to create dashboards - capability maps or Plateau to Work Package views for example) 

Obviously, not high priority.

**Comment by Phillipus** [comment]
You can access Archi's Preference Store using some Java tricks.

See https://github.com/archimatetool/archi-scripting-plugin/wiki/Accessing-Archi's-Preferences
