### ISSUE TITLE
completeness and consistency of element-type in jArch

### ISSUE THREAD

**Issue by NHSV** [archimatetool/archi-scripting-plugin#41]
### Steps to Reproduce the Behaviour (with attached test files/script)
1.
2.
3.

**Comment by NHSV** [comment]
completeness and consistency problem of element-type in jArch
Completeness issue: There is no list of element-type in the help menu or any web site
Consistency issues: (1) While display shows ApplicationComponent actual value is "application-component".            (2) Only lowercase are supported for element-type values. and (3) no trailing white space is allowed.

**Comment by NHSV** [comment]
The version of JArchi:0.4.3.20 1902121146 (from file name).
OS version:  OS Name	Microsoft Windows 10 Pro; Version	10.0.17134 Build 17134
Expected behaviour: (1) Help menu enumerate all element-type values. (2) specification of naming convention (3) consistency jarchi element-type values with (a)
 display name and (b) exported element-type in .csv file.

**Comment by NHSV** [comment]
Sample Code  failing:  theConcept = model.createElement(theObject.Type,theObject.Name,myFolder); Assumin folders are mechanism to declutter info to improve the utiluisation of information through tree-traversal (exploratory Paradigm) -- Path to folder could be useful but it may loose purity. 

Data: Type:Meaning	Term:EBCDIC		 Definition:"Extended Binary coded decimal interchange coded"

**Comment by jbsarrodie** [comment]
Hi,

>Completeness issue: There is no list of element-type in the help menu or any web site

The whole documentation of jArchi is accessible on its wiki with both the logic behind it and the list of types supported : https://github.com/archimatetool/archi-scripting-plugin/wiki

>Consistency issues: (1) While display shows ApplicationComponent actual value is "application-component". (2) Only lowercase are supported for element-type values. and (3) no trailing white space is allowed.

(1) No display shows "ApplicationComponent", we instead use "Application Component" with a space. jArchi is based on the DOM/jQuery analogy (which are proven to be good architecture designed) and thus concepts names are equivalent of HTML tags and are lowercase without spaces.

>Expected behaviour: [...] consistency jarchi element-type values with [...] exported element-type in .csv file.

Both serve different purposes: CSV is meant to be a data easy to manipulate to extract/import/report, while jArchi concepts names are designed to be used as tags in collections constructors/filters.

**Comment by Phillipus** [comment]
As JB has answered. To summarise:

- jArchi documentation is available https://github.com/archimatetool/archi-scripting-plugin/wiki
- As jArchi is a work in progress the documentation can be updated by contributors
- kebab-case is used for access to concepts
- CamelCase is used for the internal EObject class types. These are used for CSV export and for the exchange format. We don't use them for jArchi

Thanks for your observations, but as we won't be changing this I'll close this issue.

If you need help with jArchi in practice the Archi forum is a useful platform to share experiences and tips.
