### ISSUE TITLE
Allow JArchi to read/update the "Strength" property on Influence relationships

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#45]
Implement get/set Strength on Influence relationships

**Comment by Phillipus** [comment]
@jbsarrodie What's the best API for this (and also access type for Access Relationship)?

We can use `attr()`:

```
// Set
selection.first().attr("influence-strength", "+++");
// Get
var strength = selection.first().attr("influence-strength");
```

But do we also want an explicit getter and setter?

```
// Set
relationship.influenceStrength = "+++";
// Get
var strength = relationship.influenceStrength
```

**Comment by Phillipus** [comment]
`attr("key")` is not so easy when you already have a single object, as you have to wrap it in a `$(obj)` collection:

```
var relationship = ...;
var strength = $(relationship).attr("influence-strength");
```

**Comment by jbsarrodie** [comment]
My preference (at JS level) is for explicit getter and setter for object and attr() for collections. But instead of managing this at Java level we should be able to do it through JS (we could catch the "non existent attribute or method" error and then call the underlying Java attr() without officially exposing it.

BTW - If we aligne on official ArchiMate specs wording with Archi 5, then what we call properties should be renamed to attribute, thus prop() and attr() might be switched...

**Comment by Phillipus** [comment]
> But instead of managing this at Java level we should be able to do it through JS (we could catch the "non existent attribute or method" error and then call the underlying Java attr() without officially exposing it.

Not sure I understand.

**Comment by jbsarrodie** [comment]
I'll find you an example....

**Comment by Phillipus** [comment]
OK, but the code that attr() calls to get and set this is already written (setInfluenceStrength(), getInfluenceStrength()) so it's just a matter of making those methods public and it's already done.

**Comment by jbsarrodie** [comment]
In this case you can make them public (I thought you did it differently, without creating those methods).

**Comment by Phillipus** [comment]
Well, rather than clog up the attr() method with more code the attr() methods call those ones. It's the same pattern as getSource and getTarget().

So the answer is have both - attr() and set/get

**Comment by Phillipus** [comment]
So I was writing the methods:

getInfluenceStrength()
getAccessType()
setInfluenceStrength()
setAccessType()

and then I thought rather than writing individual methods for these attributes (one day there may be more) wouldn't it be better to have one getAttribute(att) and one setAttribute(att, val) method that could then deal with all cases? And then of course we already have them - attrr(att) and attr(att, val) except that those only work for a collection. Are we committed to that?

**Comment by Phillipus** [comment]
Implemented in 0.4.4

**Comment by jbsarrodie** [comment]
Some post close comment ;-)

>Are we committed to that?

Not really, or maybe not sure that I really understand...

>and then I thought rather than writing individual methods for these attributes (one day there may be more) wouldn't it be better to have one getAttribute(att) and one setAttribute(att, val) method that could then deal with all cases?

While thinking about the API, we have to remember that the target language is not Java but JavaScript. In JS, you can "parametrize" any attribute name. For example, instead of accessing `someObject.someAttribute`, you can access `someObject["someAttribute"]`, so exposing a `getAttribute(attr)` (or anything similar) is not needed and even unwanted as this duplicates a more generic and native way of doing it in JS.

**Comment by jbsarrodie** [comment]
Cont'd

Nashorn implements [__noSuchProperty__](https://www.baeldung.com/java-nashorn), so we should be able to use this to automagically trap access to object properties that have no getter/setter and call a method that accesses eObject's attributes of the same name. I'm experimenting...

**Comment by Phillipus** [comment]
OK, but where to put the magic __noSuchProperty__ ?

**Comment by jbsarrodie** [comment]
> OK, but where to put the magic **noSuchProperty** ?

By design it should be in our init.js, but maybe we can define it in Java and it will then be used (that's what I'm trying at the moment)

**Comment by Phillipus** [comment]
I think I tried this before and couldn't make it work.

**Comment by Phillipus** [comment]
`__noSuchProperty__` has to be defined as a function of every JS object. I even tried to make this a Java method.

**Comment by Phillipus** [comment]
I don't think it's possible. I tried a few things, including trying to access the prototype of a jArchi class, but that's not possible.

It seems you can only implement `__noSuchProperty__` on a native JS object, not a Nashorn object.

**Comment by Phillipus** [comment]
> and call a method that accesses eObject's attributes of the same name. 

That's possible, but we don't want to directly expose the setter method because we need to call jArchi's setter method which has its own Undo/Redo Command.

**Comment by smileham** [comment]
Hey guys, I might be being a bit thick, but I still can't seem to get either this, or the accessType attributes to work. I'm running the Archi 4.4 beta with jArchi 0.4.4, but the attributes are undefined, and it errors when I try and use the getter method with not a function...

Here is some example code that's not working.  Right click on a view and run the script...

function getRelationships(element) {
    $(element).outRels().each(function(r){
        console.log(r.source.name+","+ r.type);
        if(r.type=="access-relationship") {
            console.log("RELA:"+r.accessType);
            console.log("RELA:"+r.getAccessType());
        }
    });
}
console.show();
console.clear();
console.log(">Begin");

$(selection).find().not("relationship").each(function(c){
    getRelationships(c);
});
console.log(">end");

**Comment by Phillipus** [comment]
Your `c` variable is actually a diagram object. You need to get the underlying concept with `c.concept`. This will then ensure that your `getRelationships` function gets the actual relationships rather than the diagram connections.

```
$(selection).find().not("relationship").each(function(c){
   getRelationships(c.concept);
});
```

`accessType` is a function of a relationship not a diagram connection.

Your example could be written as:

```js
function getRelationships(element) {
    $(element).outRels().each(function (r) {
        console.log(r.source.name + "," + r.type);
        if (r.type == "access-relationship") {
            console.log("RELA:" + r.accessType);
            console.log("RELA:" + r.getAccessType());
        }
    });
}
console.show();
console.clear();
console.log(">Begin");

$(selection).find("element").each(function (object) {
    getRelationships(object.concept);
});

console.log(">end");
```

**Comment by smileham** [comment]
Fabulous!  That catches me out every time!

Thanks for your help.

**Comment by jbsarrodie** [comment]
> It seems you can only implement `__noSuchProperty__` on a native JS object, not a Nashorn object.

Yes, I came to the same conclusion.

>That's possible, but we don't want to directly expose the setter method because we need to call jArchi's setter method which has its own Undo/Redo Command.

Of course, that would make sens only for read access to properties.

**Comment by lavenderb** [comment]
Could you please confirm that this method works for setting the text position on influence relationships?

I'm confident that the following code fragment is referencing the right element in my model
 - but although I can read the element ID and the line colour, the text position returns null.

`selection.filter("influence-relationship").each(function(c) {

	console.log("Matched: ", c.type);
	for (let property in c) { console.log(property) }

    console.log("Model ID: " + c.id);
    console.log("Text Position: " + c.textPosition);
    console.log("Line Colour: " + c.lineColor);

My guess is that `I'm not using the correct property name - but don't see anything similar in the list of properties returned.

```
`delete, getTarget, setLineWidth, getSource, setLabelVisible, deleteBendpoint, isLabelVisible, addRelativeBendpoint, 
setRelativeBendpoint, deleteAllBendpoints, getRelativeBendpoints, getLineWidth, setLineColor, getView, getFontSize, 
setFontSize, setFontStyle, getFontStyle, getFontName, setFontColor, getLineColor, getFontColor, setFontName, getConcept, 
equals, toString, hashCode, compareTo, getName, setName, getId, getType, prop, getDocumentation, setDocumentation, 
getModel, removeProp, setLabelExpression, getLabelValue, getLabelExpression

Model ID: id-8773ad5032dc4a5b8966a23e00430275, 
Text Position: undefined, 
Line Colour: #e4052d`
```

**Comment by Phillipus** [comment]
`textPosition` for a connection hasn't been implemented in jArchi yet. I'll put it on the to do list. Bear in mind that every method in the Archi code has to be re-implemented for jArchi with a wrapper function.

**Comment by lavenderb** [comment]
Thanks Phil  :-)

**Comment by Phillipus** [comment]
> textPosition for a connection hasn't been implemented in jArchi yet. I'll put it on the to do list. Bear in mind that every method in the Archi code has to be re-implemented for jArchi with a wrapper function.

Done

https://github.com/archimatetool/archi-scripting-plugin/commit/9e95ed4a1e0e34b354b6e0b8d18179dad58ee80a

**Comment by lavenderb** [comment]
Thanks Phil - 
but when I try to install it using the plug-ins Manager, it complains that ‘archi-scripting-plugin-master.zip -  is not an Archi plug-in’!

I’m using v4.9.0 Build 202105121414

Any idea what the problem could be?

**Comment by Phillipus** [comment]
@lavenderb That zip file contains the source code. I haven't released a new packaged build of jArchi yet. Will do soon.

**Comment by lavenderb** [comment]
Ah – I’m too keen 😊
Thanks for adding this so quickly on such a sunny day
Rgds

**Comment by Phillipus** [comment]
> Ah – I’m too keen 😊 Thanks for adding this so quickly on such a sunny day

Yep, I'm going out on a bike ride along the beach 🌞 🏖️
