### ISSUE TITLE
Write to File and Open in Browser example script error

### ISSUE THREAD

**Issue by dseverov** [archimatetool/archi-scripting-plugin#47]
### Version of jArchi, Operating System
 

- jArchi 0.4.3.201902121146, 
- Archi 4.3.3 (201902121114), 
- MAC OS X 10.13.6 (17G5019) 

### Expected Behaviour

Browser opens without script errors

### Actual Behaviour

Browser does not open with...

> Script Error at: javax.script.ScriptException, javax.script.ScriptException: TypeError: Browser.newInstance is not a function in /Users/XXXXX/Library/Application Support/Archi4/scripts/examples/Write to File and Open in Browser.ajs at line number 31

### Steps to Reproduce the Behaviour (with attached test files/script)
1. Install com.archimatetool.script_0.4.3.201902121146.zip
2. Run `Write to File and Open in Browser` example script

**Comment by Phillipus** [comment]
Yes, that example was not updated when I changed the API. I'll fix it for the next release.

In the meantime, edit the script so it has this:

`var browser = Browser.open("file:///" + filePath, "Test");`

**Comment by Phillipus** [comment]
Fixed in latest build.
