### ISSUE TITLE
'selection' is empty when no views are opened but script invoked from context menu

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#48]
### Version of jArchi, Operating System
Archi 4.4.0 & jArchi 0.4.4 (latest codebase)
Archi 4.3.3 & jArchi 0.4.3

### Expected Behaviour
`selection` should reflect curent selection

### Actual Behaviour
`selection` is empty when no views are opened

### Steps to Reproduce the Behaviour (with attached test files/script)
1. Create a new empty model. This will also create and open a `Default View`
2. Run this simple script: `console.log(selection)` from the context menu on `DefaultView` in the model tree: it works and displays `[archimate-diagram-model: Default View]`
3. Close `Default View`and retry the same script from the context menu on `DefaultView` in the model tree: it simply displays `[]`

**Comment by Phillipus** [comment]
Until this can be investigated, click on another viewpart in the workbench and back again to the model tree.

**Comment by Phillipus** [comment]
ArchiScriptPlugin#partClosed:

Try this:

```
    public void partClosed(IWorkbenchPart part) {
    }
```

Not sure of any side effects

**Comment by Phillipus** [comment]
I've come up with a fix now. Should be OK. Re-open if not.
