### ISSUE TITLE
Should .delete() on a relationship object remove it from the model?

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi-scripting-plugin#50]
I thought .delete() on a relationship would remove it from the model, not just from the view? Or have I missed something?

```javascript
selection.filter("application-function").rels("composition-relationship").each(function(obj) {
	console.log('Deleting relation: ', obj.name);
	obj.delete();
});
```

### Version of jArchi, Operating System
MacOS 10.14.4
Archi 4.4.0
jArchi version 0.4.4.201903221626 

### Expected Behaviour
.delete() to delete a relationship from the model

### Actual Behaviour
.delete() removes the relationship from the view, but remains in the model. 

### Steps to Reproduce the Behaviour
1. Unzip and open the sample model
2. Grab the script from attached or cut and paste from the note on the diagram.
3. Select any application function and run the script. 

![image](https://user-images.githubusercontent.com/18450552/55550067-46597e80-56cf-11e9-9c66-c51d81625a0e.png)

[DeletingRelationships.archimate.zip](https://github.com/archimatetool/archi-scripting-plugin/files/3043092/DeletingRelationships.archimate.zip)

[test.ajs.zip](https://github.com/archimatetool/archi-scripting-plugin/files/3043070/test.ajs.zip)

**Comment by Phillipus** [comment]
If the selected object is a diagram connection, no. If the selected object is a concept then yes.

You need:

`obj.concept.delete();`

Because `obj` is a diagram connection.

An ArchiMate Diagram Connection (or Object) is a UI object containing:

- a reference to the underlying concept
- UI information (color, size, etc)

So if your selection comes from a diagram it's a UI object and you need to access the referenced ArchiMate concept. If your selection is from the Models Tree it's an ArchiMate concept. In fact, in that case `obj.concept` will return itself. So you can always use `obj.concept` on ArchiMate visual objects and concepts.

**Comment by Phillipus** [comment]
@jbsarrodie Perhaps we need to make it clearer about the distinction between diagram objects and underlying concepts? I guess the confusion is because the selector "relationship" implies you're getting the concept.

**Comment by rich-biker** [comment]
Thanks. That did it, of course. Yes please - a deeper mention of this in the plugin wiki would be great.

**Comment by Phillipus** [comment]
> Yes please - a deeper mention of this in the plugin wiki would be great.

This is not aimed at you personally, but a general point, that I think this is a perfect case where the jArchi community might add some things to the wiki to help. The wiki could probably use some more work overall.

**Comment by rich-biker** [comment]
No problem.. I'll see what I can do to help too, if I can.

**Comment by Phillipus** [comment]
> No problem.. I'll see what I can do to help too, if I can.

Thanks! Perhaps my explanation above might be a start?

**Comment by rich-biker** [comment]
Of course. Meanwhile, there is some (work in progress?) link near delete() on the wiki, but it's broken? I need to work out how to fork/update etc. before I can help. 

<img width="760" alt="Screenshot 2019-04-04 at 12 42 34" src="https://user-images.githubusercontent.com/18450552/55553294-b66c0280-56d7-11e9-9833-fd96fbfeb845.png">

**Comment by Phillipus** [comment]
I thought anyone could edit the wiki? Need to investigate.

**Comment by rich-biker** [comment]
Nope.. I looked for an edit button, but this must have the privileges closed down.

**Comment by Phillipus** [comment]
Ugh...and there's me wondering why no-one contributes to the wiki.  :-)

Can you try again?

**Comment by rich-biker** [comment]
Ha ha.. yes it's all ok now. I've just done an edit in that area. I'll check the broken link now too. I suspect there was an intention to create such a sub section.

**Comment by Phillipus** [comment]
OK, thanks. I think, though, that the whole notion of diagram object/connection vs. concept is more generalised than just for delete() actions.
