### ISSUE TITLE
Feature Request: 'visible=true/false' flag on visual objects

### ISSUE THREAD

**Issue by GuyWicks** [archimatetool/archi-scripting-plugin#53]
Feature request:

Add a boolean "visible" flag to visible objects to allow temporary (through the GUI) programmatic (via jArchi) hiding of items / objects / groups.

My particular use case is when I'm using jArchi to generate colour views, I want to be able to show a "Key" to the colours. I do this by having dummy concepts with the correct property values that I place at the bottom of the view.

I have several different 'colour view' options (project status, strategic rating, life-cycle etc) and each has different colours and key.  It would be useful to be able to hide / make visible the correct key concepts within the script.

There are "workarounds" I can use (auto create/delete, overlapping and use opacity, but these are ugly and difficult to maintain.

![image](https://user-images.githubusercontent.com/12052236/58806313-cfc4f880-860d-11e9-85d8-50bd46af1b8c.png)

(Apologies for hitting return too quickly - but nice to have a reply within 30 seconds!)

**Comment by Phillipus** [comment]
Hi, could you add some more detail in the comment for this FR?

**Comment by Phillipus** [comment]
This would require that objects are invisible in the main Archi code core API. jArchi just reflects that API.

**Comment by Phillipus** [comment]
I'll close this as this is not jArchi.
