### ISSUE TITLE
Feature request: Folder management and moving objects

### ISSUE THREAD

**Issue by davidsara** [archimatetool/archi-scripting-plugin#54]
Hello, is it possible to move a view to different folder using jArchi? I've tried many options but none worked.

I have one repository with many projects and I like to automate deleting views and elements not related to this project, and also move project views to the root of Views folder for easy navigation.

Thanks!
David

**Comment by Phillipus** [comment]
Hi, folder management and moving objects isn't implemented in jArchi at the moment. Something perhaps for a future version.

**Comment by davidsara** [comment]
OK thanks for the info. Can I change this to feature request or it is not needed?

**Comment by Phillipus** [comment]
Yes, change this to a generalised feature request of moving objects in folders.

**Comment by Phillipus** [comment]
This should be covered by the latest 0.6.0 release using the `Folder#add(object)` method. You can now add a concept, view or sub-folder with this method. If the object already has a parent folder, it is moved to the new parent folder.
