### ISSUE TITLE
Feature Request: Add an ability to execute a program on the system

### ISSUE THREAD

**Issue by Carl4** [archimatetool/archi-scripting-plugin#55]
I've written some external software that mirrors Archi objects to an issue tracking site. I'd like to be able to script that process.  The approach would look something like this: 

``` js
/*
 *
 * This file is intended to perform offline processing of Archimate files.  The process is as follows:
 *   1. Save the current file
 *   2. Run an external program
 *   3. Reload the changes from the file
 */
// Save the model path.
var filePath = model.getPath();

// Save the model
model.save();
console.log('saved')

// Run the script.
$.fs.runCommand(my_python_script, filePath)

// Reload the model.
$.model.load(filePath).setAsCurrent();
console.log('reloaded')
```

I think the FS module seems like the most reasonable place for such a capability, but I'm not too handy with Java.  What do people think?

**Comment by Phillipus** [comment]
Is it possible to run the external command from plain JavaScript? If your suggestion was implemented, this is basically what would be implemented behind the API method.

**Comment by jbsarrodie** [comment]
Wouldn't it be easier to run Archi headless using ACLI ?

**Comment by Carl4** [comment]
@Phillipus Executing a filesystem command is certainly not permitted from a web browser implementation of JavaScript, but probably from NodeJS.  I'm not sure what the security boundaries are on the JavaScript interpreter jArchi uses.

@jbsarrodie I'm not familiar with ACLI, but my objective here is to more closely integrate the issue tracking with the Archi editor. I'd like a systems engineer editing documents to be able to synchronize their requirements with the requirements being tracked in external issue trackers.

**Comment by Phillipus** [comment]
See https://github.com/archimatetool/archi/wiki/Archi-Command-Line-Interface

You could create a bash script / batch file to call jArchi and the system calls.

**Comment by Phillipus** [comment]
Added `exec()` to jArchi 0.8.0 could be used for this?
