### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by robkamp** [archimatetool/archi-scripting-plugin#56]
As we can develop the content for the Archimate Script in Visual Studio Code it would be nice if there would be an extension for VS to allow for easy editing of Archimate Scripts.

**Comment by Phillipus** [comment]
I've set mine up to use *.ajs files in my settings.json file:

```
"files.associations": {
     "*.ajs": "javascript"
 }
```

Other than that it's plain JS editing.

**Comment by Phillipus** [comment]
This must win the "quickest feature request to be opened, resolved and closed" award. :-)
