### ISSUE TITLE
Feature Request: Expose Reference Views in the jArchi API

### ISSUE THREAD

**Issue by rich-biker** [archimatetool/archi-scripting-plugin#58]
I would like to be able to access the View that is represented by a Reference View item. This needs to be exposed by the jArchi API to work. 

e.g. 

```js
// find the views this grouping composes
   $(grouping).children().each(function(linkedView) {
      if ((linkedView) && (linkedView.type == 'archimate-diagram-model' )) {
          console.log ("View: ", linkedView.name, " > ", thisView.id); // this gives me the name and id of the View Reference, not the view itself.
         var bytes = $.model.renderViewAsBase64(linkedView, "PNG"); // this therefore fails
   // etc
   }	
});
```

**Comment by Phillipus** [comment]
Will take a look at this soon(ish).

**Comment by Phillipus** [comment]
What's needed for View Reference objects is the equivalent of what we have now for objects in a View - `object.concept.id`.

For the next version of jArchi I'll add `linkedView.refView` so you can reference its id with `linkedView.refView.id`.

**Comment by Phillipus** [comment]
Done
