### ISSUE TITLE
Attributes for DiagramModelComponentProxy are inconsistent

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#6]
Hi,

While working with a colleague, I nooticed that:
- Most attributes for DiagramModelComponentProxy are accessible only through attr() on a collection and not directly through getters/setters
- Most attributes for DiagramModelComponentProxy have hyphen in they names, making it impossible to create getters/setters

I guess we should rework this for final version

**Comment by Phillipus** [comment]
Yep, attr() was public for a while, then became protected so it it's now exposed only via a collection. One could do:

$(dmc).attr("font-color");

**Comment by Phillipus** [comment]
Because I thought we were going to use attr() for attributes?

**Comment by jbsarrodie** [comment]
Yes one could do this, but it would be good if all attributes where accessible directly too... with a same name, like 'name', 'documentation'...

I'll work on a patch for tha, but this will be a breaking change as I will have to switch attrbute name to camelcase so that getters/setters can be created.

**Comment by Phillipus** [comment]
I can do it.

The reason I went with kebab case was to be like CSS.

Can we have both? attr("font-color") and getFontColor() ?

**Comment by Phillipus** [comment]
And I need to write unit tests for the changes.

**Comment by jbsarrodie** [comment]
I have to think  bit about it.....

**Comment by Phillipus** [comment]
Assuming that DiagramModelComponentProxy#attr() stays non-public then the options are:

- add get() and set() methods for the missing attributes
- (and) change the attr() strings to camel case to be consistent with the get() and set() methods.

I'm fine with any changes.

**Comment by jbsarrodie** [comment]
>Assuming that DiagramModelComponentProxy#attr() stays non-public then the options are:
>- add get() and set() methods for the missing attributes
>- (and) change the attr() strings to camel case to be consistent with the get() and set() methods.
>I'm fine with any changes.

That's the way to go. I've checked DOM API and camelCase is the norm: kebab-case is used only inside CSS.

**Comment by Phillipus** [comment]
I'll do this later today.

**Comment by Phillipus** [comment]
This is done now.
