### ISSUE TITLE
Cannot get note text from visual object in model group

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi-scripting-plugin#61]
### Version of jArchi, Operating System

0.6.0, Windows, Archi 4.6 Beta 4

### Expected Behaviour
Script logs the text of the note to the console twice

### Actual Behaviour
When using the .children() method on the diagram-model-group, the text of the Visual Object is "undefined"

### Steps to Reproduce the Behaviour (with attached test files/script)
1. Create new view
2. Add empty diagram model group to view
3. Add note to diagram model group
4. Enter text into note
5. Execute test script file

```console.show();
console.clear();
console.log("Notes");
console.log("Not Working");
$(selection).find('diagram-model-group').children().each(function(note){console.log(">"+note+"--"+note.type+"--"+note.fontName+"--"+note.text)});
console.log("Working");
$(selection).find('diagram-model-note').each(function(note){console.log(">"+note+"--"+note.type+"--"+note.fontName+"--"+note.text)});```

**Comment by jbsarrodie** [comment]
Just tested and I can confirm this weird behavior.

In fact the returned class is not the same. If you change a bit your script to:
````js
console.clear();
console.log("Notes");
console.log("Not Working");
$(selection).find('diagram-model-group').children().each(function(note){console.log(">"+note+"--"+note.type+"--"+note.fontName+"--"+note.text+'--'+note.getClass())});
console.log("Working");
$(selection).find('diagram-model-note').each(function(note){console.log(">"+note+"--"+note.type+"--"+note.fontName+"--"+note.text+'--'+note.getClass())});
````

Then we get this:
````
Notes
Not Working
>diagram-model-note: --diagram-model-note--Sans--undefined--class com.archimatetool.script.dom.model.DiagramModelObjectProxy
Working
>diagram-model-note: --diagram-model-note--Sans--Ma note--class com.archimatetool.script.dom.model.DiagramModelNoteProxy
````

And, the method `getText()` doesn't exist on class DiagramModelObjectProxy

I'll see how we can make it work

**Comment by jbsarrodie** [comment]
Fixed ;-)

Will be in next release

**Comment by Phillipus** [comment]
Ah, yes. Good catch, thanks JB!

**Comment by Phillipus** [comment]
In fact there is the same in DiagramModel#children() which I've also fixed.

**Comment by Phillipus** [comment]
Fixed
