### ISSUE TITLE
Idea - associate a jArchi script to a shortcut key 

### ISSUE THREAD

**Issue by xmayeur** [archimatetool/archi-scripting-plugin#62]
Would it be possible to associate a jArchi script to a shortcut key, so that the script is executed from Archi tool using a single key stroke?

**Comment by Phillipus** [comment]
Good news. Once Archi 5 has been released and a new version of jArchi released it will be possible to edit all of Archi's key bindings and assign a shortcut key to up to ten scripts.

![assign](https://user-images.githubusercontent.com/600504/203523553-ef8c492d-8b6e-4dda-951a-3f463e6fb1ad.png)

![context menu](https://user-images.githubusercontent.com/600504/203523582-6c8f333d-56e9-4d81-9897-a4e2d2830bf6.png)

![edit bindings](https://user-images.githubusercontent.com/600504/203523600-0c3bb5df-ece9-40c0-9fd9-8ea3e2b4f9ac.png)

**Comment by xmayeur** [comment]
Super, it is a big improvement to jArchi ! I like it a lot and I am keen to test it as soon as available.

What are the other expected changes in Archi 5 ?

Regards,


Xavier Mayeur

**Comment by Phillipus** [comment]
> What are the other expected changes in Archi 5 ?

ArchiMate 3.2 and much more. Take a look at the commit histories:

https://github.com/archimatetool/archi/commits/master
https://github.com/archimatetool/archi/commits/archimate32

**Comment by Phillipus** [comment]
And before anyone asks "why only 10 key assignments" there are technical reasons to do with the way Eclipse handles key bindings.

A key binding has to be assigned to an Eclipse Command and these Commands have to be created first. We create 10 dummy Commands for this, and I think any more than this and the Key bindings dialog will get crowded. I suppose we could do 12, but can anyone remember that many key shortcuts?

**Comment by Phillipus** [comment]
This is done.
