### ISSUE TITLE
Support for Groovy Scripting

### ISSUE THREAD

**Issue by grrolland** [archimatetool/archi-scripting-plugin#64]
### Version of jArchi, Operating System
Archi 4.6.0, jArchi 060, Windows 10

### Expected Behaviour
It will be great if jArchi support Groovy Script. For those who are familiar with Java language and library, I think it could be a force of adoption.

I wrote a fork which support Groovy, I would be please to share it with you.

Best regards,

**Comment by jbsarrodie** [comment]
Hi, I'm sorry but this has been discussed some years ago and the choice was made to use JavaScript and jQuery paradigm instead.

So closing as this won't be implemented.

But of course you are free to create a separated plugin for that. It can even be hosted under [archi-contribs organization](https://github.com/archi-contribs/) if you want.

**Comment by grrolland** [comment]
ok, thanks for your quick answer :-(

If you have some time, a look on my implementation would be very appreciate.

Thanks.

**Comment by jbsarrodie** [comment]
>If you have some time, a look on my implementation would be very appreciate.

I'll do :-)

**Comment by Phillipus** [comment]
I can see that replacing Nashorn with Groovy is possible from your code, and it would be possible to provide options for both, as I can see in your code. But the main issue for us is one of supporting it. We already spend a lot of time supporting users with their JS scripts and figuring out how to do things in JS. If we added Groovy support as well then it would take even more time.

What I suggest is you create a fork project. Then see if there is any interest in using Groovy. You could then support it.

**Comment by Phillipus** [comment]
BTW - I did look at the code and I can appreciate your work. As I said, it's that our support burden would double, :-)

**Comment by grrolland** [comment]
I understand that, no problem !!

Thanks for the commment !

**Comment by Phillipus** [comment]
Perhaps the main jArchi code could be slightly refactored to support an extension so that a Groovy plugin could be added that could replace the startup and invocation code. Then you could just distribute the Groovy part and not all of the jArchi code.

(I could do the jArchi part, but I'm way too busy right now with other things)

**Comment by jbsarrodie** [comment]
>Perhaps the main jArchi code could be slightly refactored to support an extension so that a Groovy plugin could be added that could replace the startup and invocation code. Then you could just distribute the Groovy part and not all of the jArchi code.

My issue with this is that it is not only a question of language, it is the API itself which is designed with JS in mind: we leverage several nashorn features (getter and setters converted to attributes and several others) and part of the environment is dependant on an `init.js`.

So IMHO this is not going to work as simply as that. And TBH I don't see any traction on Groovy anymore so don't see any advantages in doing so.

**Comment by Phillipus** [comment]
Good points.

**Comment by grrolland** [comment]
> My issue with this is that it is not only a question of language, it is the API itself which is designed with JS in mind: we leverage several nashorn features (getter and setters converted to attributes and several others) and part of the environment is dependant on an init.js.

I make a port of init.js (init.groovy) and I think all the features are present. I port successfuly the "CreateAppServicePattern.ajs" (https://gist.github.com/gevaertw/540c64dec4e2b0955b6e3d4fc5eb54b1) with all functionnality. 
 
But if there is really no traction to Groovy it really the good point. I make this fork because Javascript is just a pain when I have to import libraries. The behaviour of Nashorn is really weird and painful in this case.

**Comment by grrolland** [comment]
Here is the code for CreateAppServicePattern.groovy
`/*
jArchi Script to create default application pattern into the active model.  It creates the objects and relations.
It puts all objects into a folder per application and creates a view.
*/
 

println "Creating Default Application Pattern"

//Pop up for application name, and check if that is already in the model
def appName = prompt("Name of the application to create", "My Application Service");


def applicationServiceRead = appName
def applicationComponentRead = appName + " Application Component"
def applicationComponentDataRead = appName + " Application Data Component"
def appHostingServiceRead = appName + " Application hosting Service"
def dataHostingServiceRead = appName + " Data hosting Service"



// Create objects in active model
def applicationService = model.createElement("application-Service", applicationServiceRead);
def applicationComponent = model.createElement("application-Component", applicationComponentRead);
def applicationComponentData = model.createElement("application-Component", applicationComponentDataRead);
def appHostingService = model.createElement("technology-service", appHostingServiceRead);
def dataHostingService = model.createElement("technology-service", dataHostingServiceRead);

// Put objects in folder
def folder = jArchi("folder.Application").first();
def myAppFolder = folder.createFolder(appName);
myAppFolder.add (applicationService);
myAppFolder.add (applicationComponent);
myAppFolder.add (applicationComponentData);

folder = jArchi("folder.Technology & Physical").first();
myAppFolder = folder.createFolder(appName);
myAppFolder.add (appHostingService);
myAppFolder.add (dataHostingService);


// Create realtions in active model
def relationship1 = model.createRelationship("realization-relationship", "", applicationComponent, applicationService);
def relationship2 = model.createRelationship("realization-relationship", "", applicationComponentData, applicationService);
def relationship3 = model.createRelationship("serving-relationship", "", appHostingService, applicationComponent);
def relationship4 = model.createRelationship("serving-relationship", "", dataHostingService, applicationComponentData);

//Create a view with the model objects
/*Personal taste: Grid size = 10 (preset) space between objects = 3 grids = 30
an object has a default length (X) of 13 and a height (Y) of 6
so on the grid next X value = 160, next Y value is 90
*/

//Objects
def archimateView = model.createArchimateView(appName + "-Deployment");
archimateView.viewpoint = "implementation_migration";
def viewpointObject1 = archimateView.add(applicationService,10,10,-1,-1);
def viewpointObject2 = archimateView.add(applicationComponent,10,100,-1,-1);
def viewpointObject3 = archimateView.add(applicationComponentData,170,100,-1,-1);
def viewpointObject4 = archimateView.add(appHostingService,10,190,-1,-1);
def viewpointObject5 = archimateView.add(dataHostingService,170,190,-1,-1);

//Relations
def connection1 = archimateView.add(relationship1, viewpointObject2, viewpointObject1);
def connection2 = archimateView.add(relationship2, viewpointObject3, viewpointObject1);
def connection3 = archimateView.add(relationship3, viewpointObject4, viewpointObject2);
def connection4 = archimateView.add(relationship4, viewpointObject5, viewpointObject3);

//Default properties that I use
applicationService.prop("Archimate lifecycle status", "Active", false);
applicationComponent.prop("Archimate lifecycle status", "Active", false);
applicationComponentData.prop("Archimate lifecycle status", "Active", false);
appHostingService.prop("Archimate lifecycle status", "Active", false);
dataHostingService.prop("Archimate lifecycle status", "Active", false);

exit();
`
As you see, it's not very different !! It add the possibility to load all the Java ecosystem in your script !! Just put the JARs dependencies in the script directory.

**Comment by jbsarrodie** [comment]
>Javascript is just a pain when I have to import libraries

In fact, there are some polyfills that really help for this (I use several JS libs in my scripts). This is a part that should be added by default in `init.js` IMHO (I'm planning to do it but wanted more feedback before).

>It add the possibility to load all the Java ecosystem in your script !!

But this is also true with Nashorn: you can access any JAVA classes, it seems to me that we can even use any JM bytecode based library (including java and groovy).

**Comment by Phillipus** [comment]
Re-opening this because we can do this:

> Perhaps the main jArchi code could be slightly refactored to support an extension so that a Groovy plugin could be added that could replace the startup and invocation code. Then you could just distribute the Groovy part and not all of the jArchi code.

**Comment by grrolland** [comment]
Pleased you reopen the issue.

I suggest you tou create a plugin with the dom extenstion wich coud be used by jArchi and and my groovy Script plugin. This plugin will be a common Archi scripting API extension module. 

This suggestion will provide less coupling between Scripting API and the Scripting plugin itself.

If you publish this resulting module as a default plugin of Archi (as a free downloadable binary distribution), I will remove the duplicate code in the Groovy Script Plugin and modifying my code to use this new plugin.

Regards.

**Comment by Phillipus** [comment]
> If you publish this resulting module as a default plugin of Archi (as a free downloadable binary distribution)

Not sure what you mean by this? We already make the jArchi binary freely available, together with jArchi example scripts, as a thank-you for Patreons and Paypal contributors.

The extension I would add is an extension to the Scripting plugin, not Archi itself.

**Comment by grrolland** [comment]
Perhaps I missed something, but the Archi plugins page mentioned this : 

> The source code for jArchi is freely available at GitHub, but if you would like the compiled version as a ready-to-go drop-in Archi plug-in with examples and some support then this option is available for all Patreon members and for PayPal contributors.

And I don't find any reference to jArchi (without exemple) download.

> The extension I would add is an extension to the Scripting plugin, not Archi itself.

IMHO, the design for extension concern should conduct you to provide an API Scripting plugin in Archi itself.

**Comment by Phillipus** [comment]
> IMHO, the design for extension concern should conduct you to provide an API Scripting plugin in Archi itself.

No. Absolutely not.

I already spent all of today making an extension to the jArchi code in order to support a Groovy engine. Providing an API in Archi would take far too much time.

**Comment by jbsarrodie** [comment]
_Copied from https://github.com/grrolland/archi-groovy-scripting-plugin/issues/1_

>I think there is only one way to do this : publish a Scripting API as a plugin (which is not usable without anoter language Srcipting plugin - jArchi or another), so your model will be preserved and my plugin will not duplicate your code.

The issue with what you propose is that the core of jArchi is its API (in fact the very first version of the script plugin has been created more than 4 years ago, but without a good API it was not usable, all changed when we switch to a jQuery-like API). So this has to stick with current way of distributing the plugin.

>I just want to distribute my plugin without breaking your work and the model of distribution you have chosen.

Here's how I see it:
- As stated, IMHO your plugin should extend our official scripting plugin to leverage the jArchi API and avoid duplicating the API with all potential sync issues.
- This means that for your plugin to be used, users should first get and install jArchi
- For people you work with, colleagues, and friends, you can privately share a binary version of jArchi that you've compile yourself.
- For people you don't know, you suggest them to compile jArchi themself or get the binary version through small donation. Which IMHO is fair because of the work we've put in jArchi (without which your plugin could not exist)

If we agree on this, then your code could be hosted on archi-contribs (like Herve's DB & Specialization plugins) and you could make your plugin binary available through your repository's release page.

If you want to stick with a plugin which duplicates the API then I considered this a fork and you host it on your own GitHub account but not under archi-contribs.

**Comment by Phillipus** [comment]
There's a new branch in the code called "provider". It implements an extension point to provide different `ScriptEngine`support.

A provider extends the `com.archimatetool.script.scriptEngineProvider` extension point and declares a class that implements the `IScriptEngineProvider`Java interface and its methods. This will provide to jArchi's main code:

- The provider's ID
- The provider's name
- The instance of the `ScriptEngine` to use
- The file extension to use for a script
- The icon to use for a script
- The URL of the "new" file to use for the "New Script" action
- The run method to run the script

There is one in-built provider - JS Nashorn with options for ES5 or ES6 as we have now.

I've also created a basic Groovy provider in a separate plug-in.

Once a provider is registered it will be supported in the Scripts Manager with an icon for its file type and the engine will be used when a script is run. So it's possible to have more than one engine installed for different file types (*.ajs or *.groovy)

**Comment by Phillipus** [comment]
Closing this.
