### ISSUE TITLE
Nashorn Support query

### ISSUE THREAD

**Issue by smileham** [archimatetool/archi-scripting-plugin#67]
### Version of jArchi, Operating System
Archi: 4.6.0
jArchi: 0.7
JRE: 11.0.3+7
OS: Windows 10

### Expected Behaviour
jArchi Script runs without warning

### Actual Behaviour
Warning is raised in jArchi console:
Warning: Nashorn engine is planned to be removed from a future JDK release

### Steps to Reproduce the Behaviour (with attached test files/script)
1. Create new jArchi script
2. Run Script

**Comment by Phillipus** [comment]
My bad, that message normally is not sent to the jArchi console. I'll fix it for the next version.

**Comment by Phillipus** [comment]
Fixed in 0.7.1 - binary available in the usual places.
