### ISSUE TITLE
Extend Feature - Add a way to merge two relationships

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#68]
This should have been part of #51 but has never been implemented. Of course this should follow the same API.

I have to see what's involved (is it really different to merging elements)

**Comment by Phillipus** [comment]
> I have to see what's involved (is it really different to merging elements)

- What does it mean to merge relationships? 
- They must have the same source and target concepts?
- Must be of same relationship type?

**Comment by jbsarrodie** [comment]
> * What does it mean to merge relationships?
> * They must have the same source and target concepts?
> * Must be of same relationship type?

Exactly

**Comment by Phillipus** [comment]
OK. But why are there relationships of this kind? Duplicates? What is the aim?

**Comment by jbsarrodie** [comment]
> OK. But why are there relationships of this kind? Duplicates? What is the aim?

This happens in several occasions:
- Some people might create a new relationship on a view while a similar relationship was already existing on the model. This is less prone now that Archi warns you if a relationship of the same type/ends already exists, but some models have been created using previous version of Archi and exhibit this issue.
- You might start modelling at a too detailed level (e.g. create flows between applications based on the exact data object transfered) and then decide to move abstraction up (e.g have only one single flow between two applications, with a name/documentation listing all data objects involved)
- When you merge to elements (A and B) while both of them had a relationship with another element (C). You end up with two relationships (e.g. A -> C). This is the case one of my colleagues is facing, and he has dozens of relationships to merge.

**Comment by Phillipus** [comment]
OK, so we can use a similar API to element merge?

`relationship.merge(otherRelationship)`

But do we want to then delete the other relationship after the merge?

**Comment by jbsarrodie** [comment]
> OK, so we can use a similar API to element merge?
> 
> `relationship.merge(otherRelationship)`

Yes

> But do we want to then delete the other relationship after the merge?

No (we don't delete it when merging two elements). People can decide to do it explicitely in their script if needed (that what my script shared on Gist does)

**Comment by Phillipus** [comment]
What about deleting diagram connection instances of the other relationship?

**Comment by jbsarrodie** [comment]
> What about deleting diagram connection instances of the other relationship?

Not sure to understand. Like with element, the diagram connection instances pointing to `otherRelationship` must point to `relationship` after the merge, and `otherRelationship` should be left in the model, but not used in any view.

**Comment by Phillipus** [comment]
Got it.

(Brain fog today)

**Comment by Phillipus** [comment]
Ready for testing in branch `merge-relationships`

**Comment by Phillipus** [comment]
Merged to master
