### ISSUE TITLE
New Feature - Add a way to get the root of script folder

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#69]
It would be nice to be able to quickly get the path used for the root script folder. This would allow to create script which reference some script libraries without having to copy those libraries in each script sub-folder.

I would suggest to make it available through a variable named `__ROOT__` (similar to `__DIR__`).

I'll work on it !

**Comment by Phillipus** [comment]
Added to jArchi 0.8.0.
