### ISSUE TITLE
model.addElement 

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#7]
model.addElement in not in the jArchi documentation

**Comment by Phillipus** [comment]
It was added earlier today. Can you confirm?

https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-API-Documentation#creating-and-deleting-model-concepts

**Comment by gedwardroberts** [comment]
yes...


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com
