### ISSUE TITLE
exit() should not try to print the exit line (it is always the wrong one)

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#70]
the `exit()` function prints something which should be the script line at which it got called, but in that this never work because `__LINE__` (or equivalent) is in fact evaluation at the creation of the `exit()` function, not at its runtime. That's why it always indicate _Exited at line number **76**_

**Comment by Phillipus** [comment]
That's in `RunArchiScript#error()`. Either we figure out how to get the correct line number or remove that message and just say "Exited".

**Comment by jbsarrodie** [comment]
>Either we figure out how to get the correct line number or remove that message and just say "Exited".

I tried during a lot time to fix a similar issue but never succeeded. We should just print "Exited".

**Comment by Phillipus** [comment]
Fixed
