### ISSUE TITLE
Mark script folders to not appear in "Scripts" menu

### ISSUE THREAD

**Issue by steverumsby** [archimatetool/archi-scripting-plugin#72]
I have quite a lot of scripts for various purposes. Only some of them are useful from the "Scripts" right-click menu in a view. Currently for me that menu is quite cluttered. It would be nice to be able to mark folders in the scripts manager as relevant for the pop-up menu so that only a subset of my scripts appear there.

Does that make sense?

Thanks,
Steve.

**Comment by Phillipus** [comment]
I can see how tuning the right-click menu contents might be helpful. Not sure how to implement that, though since it's taking it from the file contents in the scripts folder. Don't know where one would store the metadata needed to mark it as a "do/do not show". We'll keep this one open and have a think about it. It might be part of further work on script management.

**Comment by steverumsby** [comment]
Would something simple like creating a ".nomenu" file in the folder work?

**Comment by steverumsby** [comment]
Or, thinking about more general script management, maybe better yet a dot-file with more general information about the scripts in the folder. For example, some scripts are only relevant for view elements, some only relevant for views. Maybe the context of the right-click could change the contents of the script menu?

**Comment by jbsarrodie** [comment]
One simple option could be this:
- Folders or script files starting with a dot are hidden from the menu
- Add an option to the Scripts Manager to "(un)hide folder or script from menu" which simply adds/removes the leading dot
- In the Scripts Manager: use an alternative Icon for "hidden" folders or script
- In the Scripts Manager: for folder and files with a leading dot, don't show this dot in the folder/file name

So this leading dot would be only visible from the OS file manager.

**Comment by steverumsby** [comment]
That's a nice, simple solution. I like it :-)

**Comment by jbsarrodie** [comment]
> That's a nice, simple solution. I like it :-)

Well, I really like the KISS principle, so if Phil is aligned with this proposal, then we see how to move on that way. I personaly have several things to contribute to jArchi, so I might work on it (no ETA though).

**Comment by Phillipus** [comment]
I'm thinking about it... ;-)

**Comment by jbsarrodie** [comment]
> I'm thinking about it... ;-)

Hmm. Makes me think that in 5min you'll say "done..."

**Comment by Phillipus** [comment]
> Hmm. Makes me think that in 5min you'll say "done..."

Not this time..tonight is Leffe night! 

![image](https://user-images.githubusercontent.com/600504/82351108-0e58ec00-99f4-11ea-9f3e-f111580b4fa9.png)

**Comment by jbsarrodie** [comment]
And during this time, I'm in lockdown 200km away of my beers :-(

**Comment by Phillipus** [comment]
But consider the implications of adding a dot to files.

- File will be hidden to OS on Mac and Linux
- If a script references another script file

Another way is to declare a hierarchy in the script header comment.

```
/* 
 * Menu: Hello > Phil > My Menu
 * Author: Foo Bar
 * License: EPL 1.0
 */
```

**Comment by jbsarrodie** [comment]
> * File will be hidden to OS on Mac and Linux

I don't see this as a big deal (quite coherent in fact), but any other leading character would do it.

> * If a script references another script file

Hmm, that's a real issue. Of course we could create a wrapper for `load()` that would simply check if the file exists, and if not look for the same name with a dot added.

>Another way is to declare a hierarchy in the script header comment.

I was thinking about using the header comment, but this works only for scripts, and maybe people will want to hide everything in a folder. But this could also serves other purposes like providing alternate (potentially translated) label...

**Comment by jbsarrodie** [comment]
> but this works only for scripts

Looking at your example, I don't think providing the whole hierarchy is a good thing because different people will want to organize their scripts differently.

**Comment by Phillipus** [comment]
> Looking at your example, I don't think providing the whole hierarchy is a good thing because different people will want to organize their scripts differently.

I agree.

But I want to brainstorm other possible ideas. :-)

Here's another idea:

- A special folder in the scripts home folder, that denotes the root of the right-click menu. Everything in here shows in the menu.

**Comment by steverumsby** [comment]
> Here's another idea:
> 
> A special folder in the scripts home folder, that denotes the root of the right-click menu. Everything in here shows in the menu.

I organise my scripts so that the main scripts tend to be just calls to functions contained in included files. These included files live in a "lib" subdirectory. These libraries are part of what I want to omit from the scripts menu. If we go for this system, I'd want to house the libraries elsewhere, but then including them becomes a pain because they're not just __DIR__ + "/lib/script.ajs"

And even if referencing them was made easy somehow, separating them this way doesn't feel right.

**Comment by steverumsby** [comment]
> > Another way is to declare a hierarchy in the script header comment.
> 
> I was thinking about using the header comment, but this works only for scripts, and maybe people will want to hide everything in a folder. But this could also serves other purposes like providing alternate (potentially translated) label...

If the script header was used to build up the scripts menu, rather than to remove things from it, this would be fine wouldn't it? It is only going to have scripts in it anyway. It does mean the scripts menu would be empty by default, unless you auto generate a "Menu" comment when a script is created, based on the folder structure so that you automatically get what you get now, but script authors can choose to change that by omitting  scripts, or placing them elsewhere in the hierarchy.

Could this be used to place a script in multiple places in the scripts menu, with multiple "Menu" comment lines? That could be useful, maybe.

**Comment by jbsarrodie** [comment]
> * A special folder in the scripts home folder, that denotes the root of the right-click menu. Everything in here shows in the menu.

I don't really like this because I think it constraints things a bit too much.

>These libraries are part of what I want to omit from the scripts menu.

@steverumsby Personnaly I don't use `.ajs` extensions for my libraries, but simple `.js`. As the menu only include files with `.ajs` extensions, they are automatically hidden.

So here is my updated proposal:
- By default, only `.ajs` scripts are made visible in the menu. If a folder contains no visible `.ajs` files, then this folder is not visible in the menu (this is current behavior).
- New: If folder contains a file named `hidden`, then it is not visible in the menu. This `hidden` file is created/deleted through an option in Scripts Manager.
- New: If a script contains `//menu:hidden` in the begining of a line, then it is not visible in the menu. This comment can be either added manually (MVP) or through an option in Scripts Manager.

**Comment by Phillipus** [comment]
@jbsarrodie That sounds better. I think if we can avoid magically renaming files it would be good.

**Comment by Phillipus** [comment]
If we call if `.hidden` then it will automatically be hidden as we don't show "." files

This gets back to the original idea:

> Would something simple like creating a ".nomenu" file in the folder work?

**Comment by Phillipus** [comment]
@jbsarrodie There's a new branch `hide-folder`. Right-click on a folder in the Scripts Manager and choose the action to show or hide the folder in context menus.

**Comment by Phillipus** [comment]
Added to jArchi 0.8.0.
