### ISSUE TITLE
Implement text alignment and positions

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#74]
I'm implementing `object#setTextAlignment()` and `object#setTextPosition()`

Internally the values of these are integers:

```
    int TEXT_ALIGNMENT_LEFT = 1;
    int TEXT_ALIGNMENT_CENTER = 2;
    int TEXT_ALIGNMENT_RIGHT = 4;

    int TEXT_POSITION_TOP = 0;
    int TEXT_POSITION_CENTRE = 1;
    int TEXT_POSITION_BOTTOM = 2;
```

@jbsarrodie - for jArchi should we implement the API

1. Using these same integer values (`object.textAlignment = 1`)

or 

2. Using a string that is mapped to these values (`object.textAlignment = "LEFT"`)

or

3. Declare some consts in `init.js` (`const LEFT = 1`).

**Comment by Phillipus** [comment]
Also, the same question for Note and Group border types:

```
    int BORDER_TABBED = 0;
    int BORDER_RECTANGLE = 1;

    int BORDER_DOGEAR = 0;
    int BORDER_RECTANGLE = 1;
    int BORDER_NONE = 2;
```

So the general question is, how do we surface these internal integers in the jArchi API?

As the same integers, or as mapped strings and/or consts?

**Comment by jbsarrodie** [comment]
> for jArchi should we implement the API
> 1. Using these same integer values (`object.textAlignment = 1`)
> or
> 1. Using a string that is mapped to these values (`object.textAlignment = "LEFT"`)
> or
> 1. Declare some consts in `init.js` (`const LEFT = 1`).

I think the best way would be 3 (which implies also 1), but maybe not through global constants but through a subobject of jArchi object:

````js
[...]
jArchi.model = jArchiModel;
jArchi.fs = jArchiFS;

jArchi.const = {
    TEXT_ALIGNMENT_LEFT : 1,
    TEXT_ALIGNMENT_CENTER : 2,
    TEXT_ALIGNMENT_RIGHT : 4,
	
    TEXT_POSITION_TOP : 0,
    TEXT_POSITION_CENTRE : 1,
    TEXT_POSITION_BOTTOM : 2,
	
    BORDER_TABBED : 0,
    BORDER_RECTANGLE : 1,

    BORDER_DOGEAR : 0,
    BORDER_RECTANGLE : 1,
    BORDER_NONE : 2,
};

Object.freeze(jArchi.const);

$ = jArchi;
[...]
````

And then:
```js
object.textAlignment = $.const.TEXT_POSITION_BOTTOM;
````

**Comment by Phillipus** [comment]
> but maybe not through global constants but through a subobject of jArchi object

Any reasons why this way and not global constants?

**Comment by jbsarrodie** [comment]
> Any reasons why this way and not global constants?

I don't know if it's good reason, but do like when things (vars/consts) are ordered and use namespace. I have the feeling that the less global vars/const we create, the better.

So not a conviction, just a feeling

**Comment by Phillipus** [comment]
Yeah, I can understand about namespacing. It's just that `$.const.TEXT_POSITION_BOTTOM` is less intuitive than just `TEXT_POSITION_BOTTOM`

How about something like this:

```
TEXT_ALIGNMENT = {
    LEFT : 1,
    CENTER : 2,
    RIGHT : 4
};

TEXT_POSITION = {
    TOP : 0,
    CENTER : 1,
    BOTTOM : 2
};

BORDER = {
    TABBED : 0,
    DOGEAR : 0,
    RECTANGLE : 1,
    NONE : 2
};
```

Then:

`object.textAlignment = TEXT_POSITION.BOTTOM;`

**Comment by Phillipus** [comment]
Added to jArchi 0.8.0.
