### ISSUE TITLE
Add global Scripts Dir constant

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#75]
As well as Nashorn's `__FILE__` and `__DIR__` we need a bound global for the root jArchi Scripts folder as set in jArchi's preferences.

It could be `__SCRIPTS_DIR__`

If so, this can easily be done by:

`ScriptEngine#put("__SCRIPTS_DIR__", ArchiScriptPlugin.INSTANCE.getUserScriptsFolder());`

So, running this script in the root folder:

```
console.log(__SCRIPTS_DIR__);
console.log(__DIR__);
```

outputs:

```
C:\Users\Phillipus\AppData\Roaming\Archi4\scripts\
C:\Users\Phillipus\AppData\Roaming\Archi4\scripts\
```

@jbsarrodie - is `__SCRIPTS_DIR__` ok?

**Comment by jbsarrodie** [comment]
> @jbsarrodie - is `__SCRIPTS_DIR__` ok?

Yes it is. Thank you!

**Comment by Phillipus** [comment]
Added to jArchi 0.8.0.
