### ISSUE TITLE
Feature  Request  Set elements id in jArchi

### ISSUE THREAD

**Issue by bozoh** [archimatetool/archi-scripting-plugin#76]
Would be nice if i can set the id via jArchi when i create an element,  and if i pass same id on creation it *NOT* create a new element

like 
model.createElement(concept, name, id) 
if it not set, id will be generated/

Will work like in CSV import
if  i set id,  and this already used (and have same concept) the element is not created, but if have other concept a error an error is displayed

**Comment by Phillipus** [comment]
What's the use case for providing an id for a concept?

@jbsarrodie We did think about supporting this. I'm not sure if there are potential dangers or not.

**Comment by jbsarrodie** [comment]
@Phillipus that's not the same use case because in this case the goal is to **not** create the element.

@bozoh I don't think we're gonna implement this as you can already create a wrapper function yourself: get $('#'+id), check if is empty and if yes, call createElement, else return the first element of the collection.

**Comment by Phillipus** [comment]
@jbsarrodie Sure, but is there a use case for specifying an id? For example, if you are using existing data.

**Comment by jbsarrodie** [comment]
> @jbsarrodie Sure, but is there a use case for specifying an id? For example, if you are using existing data.

My personal opinion on this is that we should never allow someone to set the id because this can lead to all sort of trouble. This is the pandora box we don't want to open ;-)

If you have to sync existing data, then you have to save the external id as a property, not force the internal Id of the object (and now that there is now a [good example](https://gist.github.com/jbsarrodie/77e1e6779ace738a15c0bdcf551d68ec) of doing this, it becomes easier for people)

**Comment by Phillipus** [comment]
@jbsarrodie That's fair enough.

**Comment by bozoh** [comment]
@Phillipus If you import elements from some where else, like a data base, you may use  database id  to get the right element (  avoid duplicates),  it will be more easier than check by name and type.

the only way to do that for now, is using CSV import.

**Comment by jbsarrodie** [comment]
> If you import elements from some where else, like a data base, you may use database id to get the right element ( avoid duplicates), it will be more easier than check by name and type.

Database id are internal ids in an external system, it has nothing to do with Archi internal ids. assuming anything special about an id (except that it is unique) is bad practice in software development.

The simpliest example is that you might have to get information for the same asset from multiple datasources, in such case there is no asset id per se, just asset ids in their own bounding context.

So if you synchronize model elements with an external datasource (whatever it is) you have to keep this external id in an element property.

>the only way to do that for now, is using CSV import.

The only **built-in** way is CSV import, but with a jArchi script you can do whatever you want. FWIW, I recently published a [configurable script](https://gist.github.com/jbsarrodie/77e1e6779ace738a15c0bdcf551d68ec) to do it in a better way.

**Comment by bozoh** [comment]
database id= id controlled by a external source,  not the database object id , something like, the hash of name, element type (not concept-type) and version concatenated for example

>  I recently published a configurable script to it in a better way

Yes i see, in the example, it uses elements props to get an id,  but will be the same (very similar) on what i am using now

> but with a jArchi script you can do whatever you want

well,  can't set an id  😄 
  
` element.id =  "XPTO"; element.attr('id','XPTO'); `

won't work (of course, it's read-only)

**Comment by ssherwoo** [comment]
Couldn't you use a property to set the FK to your non-Archi database?

**Comment by bozoh** [comment]
I don't have an unique property, even worst i don't have same properties to my all elements. And i don't think it's a good idea create/add a meaningless properties in the model 

meaningless properties = properties it's not related to the element,  it's related to import/sync process


but  i think that i can create the element and store the generated id in the external database 
something like

`INSERT INTO XPTO  (MODEL_ID) VALUES ( element.id)`

but if element is deleted only in the model i will have a problem 😞

**Comment by bozoh** [comment]
Other idea i have is hooks UI events  to jArchi,   something like  

relationship-drag ->  will fire all jArchi script hooked in this event when  a  relation is dragged in a view  

and if a have a way to turn on/off  this  will be great
