### ISSUE TITLE
Add support for Label Expressions

### ISSUE THREAD

**Issue by Phillipus** [archimatetool/archi-scripting-plugin#78]
I've already committed some draft support for these in the branch `label-expressions`, but we need to agree on the API.

Proposed is:

```js
// Set the label expression
object.labelExpression = expression;

// Return the label expression for an object
var expression = object.labelExpression;

// Return the value of the rendered label expression
var value = object.labelValue;
```

Example:

```js
var object = ...; // Get some visual object
object.name = "My Name"
object.documentation = "My Documentation"
object.labelExpression = "${name} - ${documentation}"
var result = object.labelValue;
console.log(result); // Result is "My Name - My Documentation"
```

Comments welcome.

**Comment by jbsarrodie** [comment]
> ```js
> // Set the label expression
> object.labelExpression = expression;
> 
> // Return the label expression for an object
> var expression = object.labelExpression;
> 
> // Return the value of the rendered label expression
> var value = object.labelValue;
> ```

Almost agree. I think the latest should be only `label` (and obviously read-only):
````js
// Return the value of the rendered label expression
var value = object.label;
````

Note: if object is a real concept, then we should maybe get and apply the expression defined on the model folder. And when object is a visual object then we get and apply in the view's context.

In addition, I think we should provide a way to execute renderer on an object without having to first change it's label expression. We could define `label(expression)`, so in fact `object.label()` would internally call `object.label(object.labelExpression)`.

**Comment by Phillipus** [comment]
>  In addition, I think we should provide a way to execute renderer on an object without having to first change it's label expression. We could define `label(expression)`, so in fact `object.label()` would internally call `object.label(object.labelExpression)`.

Those map onto the methods in `TextRenderer`:

```java
public String render(IArchimateModelObject object); // return label using the expression in the object's feature
public String render(IArchimateModelObject object, String formatExpression); // return label using the given expression
```

**Comment by Phillipus** [comment]
Proposed is now:

```js
// Set the label expression for an object
object.labelExpression = expression;

// Return the label expression for an object
var expression = object.labelExpression;

// Return the value of the object's rendered label expression
var value = object.label;

// Return the value of the given rendered label expression in the context of the object
var value = object.label(expression);
```

**Comment by Phillipus** [comment]
Merged to master
