### ISSUE TITLE
[featureRequest] Extend selectors

### ISSUE THREAD

**Issue by WatchTh1** [archimatetool/archi-scripting-plugin#79]
Is it possible to have a selector which:
1. Gives a collection of objects having specific property key, or key-value pair
2. Name regular expression
3. Documentation regular expression
4. Negative expression, such as "!flow-relationship" selects all relationships except flow.

**Comment by Phillipus** [comment]
The `filter` function of a collection is designed to fulfil all of these cases.

> 1. Gives a collection of objects having specific property key, or key-value pair

```js
var collection = $(selection).filter(
    function(object) {
        return object.prop("key") != null;
    }
)
```

> 2. Name regular expression

```js
var collection = $(selection).filter(
    function(object) {
        const regex = RegExp('Foo');
        return regex.test(object.name);
    }
)
```

> 3. Documentation regular expression

```js
var collection = $(selection).filter(
    function(object) {
        const regex = RegExp('Foo');
        return regex.test(object.documentation);
    }
)
```

> 4. Negative expression, such as "!flow-relationship" selects all relationships except flow.

```js
var collection = $(selection).filter(
    function(object) {
        return object.type != "flow-relationship"
    }
)
```

**Comment by WatchTh1** [comment]
Thanks, didn't find this funciton

**Comment by WatchTh1** [comment]
@Phillipus btw, `const` is not recognized. Seems like smth like this:
 
https://stackoverflow.com/questions/43406743/call-javascript-that-contains-const-from-java

Current examples are going into:
`Expected an operand but found const
        const regex = RegExp('^S.*');
        ^ in <eval> at line number 1`

Without const specifier goes fine. =)

**Comment by Phillipus** [comment]
I had the scripting preference set to "Nashorn ES6". It was just an example.

**Comment by WatchTh1** [comment]
Is there an option to set ES6 with jArchi ?

**Comment by Phillipus** [comment]
In Preferences.

See https://github.com/archimatetool/archi-scripting-plugin/issues/59
