### ISSUE TITLE
Inconsistency in API

### ISSUE THREAD

**Issue by jbsarrodie** [archimatetool/archi-scripting-plugin#80]
The keywork used to filter _notes_ or _visual groups_ is not the same that the one used to create them:

````js
// Getting the list of notes or groups
$(someview).find('diagram-model-note');
$(someview).find('diagram-model-group');

// Adding a note or group to a view
var note = someview.createObject("note", 10, 200, 200, 100, true);
var group = someview.createObject("group", 10, 200, -1, -1);
````

We should harminize `createObject` API call and update documentation (use `'diagram-model-note` instead of `note` and maybe keep `note` as a non documented alias for backward compatibility, same for `goup`).

**Comment by Phillipus** [comment]
Done.
