### ISSUE TITLE
Extend .createViewReference with  'autoNest' optional boolean parameter

### ISSUE THREAD

**Issue by enfeet** [archimatetool/archi-scripting-plugin#81]
Hello!
Many, many, many thanks for such great work.
Your plugin is really a 'must have' for Archi users.

It would be nice to have 2 versions of createViewReference (same as for .createobject)
https://github.com/archimatetool/archi-scripting-plugin/wiki/jArchi-Object#createobject
second one with 'autoNest' optional boolean parameter. If true the referred view object will be nested inside of any existing diagram object whose bounds surrounds the new object's bounds.

Thanks in advance.

**Comment by Phillipus** [comment]
Yes, why not, as the code is already there to do this all we need is a similar API function.

**Comment by Phillipus** [comment]
Done

**Comment by enfeet** [comment]
> Done

Thanks a lot!
