### ISSUE TITLE
jarchi add connection (non-semantic)

### ISSUE THREAD

**Issue by scott-o** [archimatetool/archi-scripting-plugin#84]
Request to enhance the jArchi plugin with the ability to add connections (non-semantic) between elements.
for example:

var g = theView.createObject("group",x1,y1);
var n = theView.createObject("note",x2,y2);
var c1 = theView.createObject("connection",g,n);

var o = theView.add(anElement,x3,y3);
var c2 = theView.createObject("connection",n,o);

**Comment by Phillipus** [comment]
Will be in next version.
