### ISSUE TITLE
failed to install jArchi

### ISSUE THREAD

**Issue by stefjoosten** [archimatetool/archi-scripting-plugin#86]
I have downloaded the jArchi-plugin by clicking on the hyperlink in the blogpost. The "Manage Archi Plug-ins" function requires that there is a `.archiplugin`-file. However, there was no such thing in the zip-file that i got as a result of downloading. So the installation of jArchi failed. Am I doing something wrong?

### Version of jArchi, Operating System
I'm using Archi 4.8 on a MacBook Pro.

**Comment by Phillipus** [comment]
For some reason the link has changed the extension to .zip. I will investigate.

You could:

1. Keep the zip file as is and use that in the Manage Archi Plug-ins dialog (select *.zip in the dialog combo filter)
2. Manually change the extension to .archiplugin

**Comment by stefjoosten** [comment]
Thanks. I tried option 2 and it works!
