### ISSUE TITLE
.concept is wrong it is .archimateConcept 

### ISSUE THREAD

**Issue by gedwardroberts** [archimatetool/archi-scripting-plugin#9]
.concept is wrong it is .archimateConcept needs to fix in documentation

**Comment by Phillipus** [comment]
Fixed already. Please recheck.

**Comment by gedwardroberts** [comment]
yes... is there.. thanks


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by gedwardroberts** [comment]
this also needs to be replaced in the table... under jArchi Object
methods...


________________________________________
G. Edward Roberts
Elparazim
http://www.elparazim.com

**Comment by jbsarrodie** [comment]
done :-)
