### ISSUE TITLE
Ability to create diagram connections

### ISSUE THREAD

**Issue by michael-tapp-vodafone-com** [archimatetool/archi-scripting-plugin#96]
I'm trying to write script where I want to create a diagram connection, for example, a connection between a note & an element. When I look in the API however, there doesn't seem to be a way to do this (unless I'm missing something).

There is createRelationship - but (as I've found) this only works for model relationships rather than visual connections
There is add(relationship) - but this wants an existing relationship and because I can't create one, it doesn't work
There is createObject - for visual objects on a diagram, but this seems to be objects only rather than relationships

Is this a missing feature? Or am I missing something?

Related too, there some visual aspects of those connections that are not available for standard relationships such as changing the connection from solid, to dotted, dashed etc and the source/target style. Again, unless I'm missing it, am I correct in thinking those aren't currently accessible from JArchi?

Thanks

Michael

**Comment by Phillipus** [comment]
Hi Michael, creating non-ArchiMate connections is on the to-do list and is being worked on:

https://github.com/archimatetool/archi-scripting-plugin/commit/a407f10a1213851cad8a1b6efddb2b7aaf67288d

Regards,

Phil

**Comment by michael-tapp-vodafone-com** [comment]
Aha, thanks Phil, I wondered as much :).

Michael

**Comment by Phillipus** [comment]
This is now in jArchi 1.1.1 released today.

**Comment by michael-tapp-vodafone-com** [comment]
Fantastic, thanks Phil.

**Comment by ainthek** [comment]
Please how do you use it ? createDiagramConnection raises error: org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (createDiagramConnection) on com.archimatetool.script.dom.model.ArchimateDiagramModelProxy failed due to: Unknown identifier: createDiagramConnection
	at <js>.:=>(Note-Expand.ajs:23)
	at com.oracle.truffle.polyglot.PolyglotFunctionProxyHandler.invoke(PolyglotFunctionProxyHandler.java:151)
	at jdk.proxy1/jdk.proxy1.$Proxy39.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at <js>.:anonymous(Note-Expand.ajs:19)

mu call is: el.view.createDiagramConnection(newNoteElement,el);

**Comment by ainthek** [comment]
ok I see the code It has been renamed in process probably, 

```
/**
     * Create and add a plain connection between two diagram components in this view and return the diagram connection
     */
    public DiagramModelConnectionProxy createConnection(DiagramModelComponentProxy source, DiagramModelComponentProxy target) {
        // Ensure that source and target diagram components belong to this diagram model
        if(source.getEObject().getDiagramModel() != getEObject()) {
            throw new ArchiScriptException(Messages.DiagramModelProxy_1);
        }
        if(target.getEObject().getDiagramModel() != getEObject()) {
            throw new ArchiScriptException(Messages.DiagramModelProxy_2);
        }
        
        return ModelFactory.createDiagramConnection((IConnectable)source.getEObject(), (IConnectable)target.getEObject());
    } 
```
Please someone update documentation in wiki ?

**Comment by Phillipus** [comment]
@ainthek It is here - https://github.com/archimatetool/archi-scripting-plugin/wiki/View#createconnection

**Comment by ainthek** [comment]
Thanx, I see it now. Somehow expected to be here as well: https://github.com/archimatetool/archi-scripting-plugin/wiki/Visual-Objects
